import { test, beforeEach, afterEach } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { tmpdir } from 'node:os'
import { env } from './fixtures/home/_copy.ts'
import { create, restore, latest, list } from '../src/backup.ts'

const KEYS = ['BARRITO_HOME', 'BARRITO_CONFIG', 'BARRITO_STATE', 'BARRITO_LOG', 'BARRITO_SHIMS']
let prev: Record<string, string | undefined>, home: string

beforeEach(() => {
  prev = Object.fromEntries(KEYS.map((k) => [k, process.env[k]]))
  home = env(fs.mkdtempSync(path.join(tmpdir(), 'bb')))
})

afterEach(() => {
  KEYS.forEach((k) => {
    if (prev[k] === undefined) delete process.env[k]
    else process.env[k] = prev[k]
  })
  fs.rmSync(home, { recursive: true, force: true })
})

const setup = (root: string) => {
  fs.mkdirSync(path.join(root, 'shims'), { recursive: true })
  fs.writeFileSync(path.join(root, 'shims', 'claude'), 'old claude shim\n')
  fs.writeFileSync(path.join(root, 'shims', 'plist-like'), 'x')
  fs.symlinkSync('claude', path.join(root, 'shims', 'agent'))
  fs.mkdirSync(path.join(root, 'LaunchAgents'), { recursive: true })
  fs.writeFileSync(path.join(root, 'LaunchAgents', 'com.tybarho.claude-router.plist'), '<plist/>')
  return {
    shim: path.join(root, 'shims', 'claude'),
    link: path.join(root, 'shims', 'agent'),
    plist: path.join(root, 'LaunchAgents', 'com.tybarho.claude-router.plist'),
  }
}

test('create: saves files, keeps symlinks as symlinks, records, writes manifest', () => {
  const files = setup(home)
  const backup = create({ ts: '2026-10-01T2030' })
  backup.save(files.shim)
  backup.save(files.link)
  backup.save(files.plist)
  backup.record('launchd', 'com.tybarho.claude-router')
  backup.record('removed', files.link)
  const manifestPath = backup.write()

  assert.equal(manifestPath, path.join(home, '.config', 'barrito', 'backup', '2026-10-01T2030', 'manifest.json'))
  assert.equal(fs.lstatSync(path.join(backup.root, '001-agent')).isSymbolicLink(), true)
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  assert.equal(manifest.files.length, 3)
  assert.deepEqual(manifest.launchd, ['com.tybarho.claude-router'])
  assert.deepEqual(manifest.removed, [files.link])
  const link = manifest.files.find((f: { symlink?: boolean }) => f.symlink)
  assert.deepEqual(link, { original: files.link, saved: link.saved, symlink: true, target: 'claude' })
})

test('restore: round-trips files, symlinks, and re-bootstraps legacy launchd', () => {
  const files = setup(home)
  const backup = create({ ts: '2026-10-01T2030' })
  ;[files.shim, files.link, files.plist].forEach((f) => backup.save(f))
  backup.record('launchd', 'com.tybarho.claude-router')
  const manifestPath = backup.write()

  // the migration then wrecks everything
  fs.writeFileSync(files.shim, 'generated by barrito\n')
  fs.rmSync(files.link)
  fs.rmSync(files.plist)

  const calls: Array<{ bin: string; args: string[] }> = []
  restore(manifestPath, {
    exec: (bin: string, args: string[]): string => {
      calls.push({ bin, args })
      return ''
    },
  })

  assert.equal(fs.readFileSync(files.shim, 'utf8'), 'old claude shim\n')
  assert.equal(fs.lstatSync(files.link).isSymbolicLink(), true)
  assert.equal(fs.readlinkSync(files.link), 'claude')
  assert.equal(fs.readFileSync(files.plist, 'utf8'), '<plist/>')
  assert.deepEqual(calls, [{ bin: '/bin/launchctl', args: ['bootstrap', `gui/${process.getuid!()}`, files.plist] }])
})

test('restore: corrupt manifests throw an actionable error, not a crash', () => {
  const files = setup(home)
  const backup = create({ ts: '2026-10-01T2030', dir: path.join(home, 'custom') })
  backup.save(files.shim)
  const manifestPath = backup.write()
  const raw = JSON.parse(fs.readFileSync(manifestPath, 'utf8')) as Record<string, unknown>

  const reject = (): void =>
    assert.throws(() => restore(manifestPath, { exec: () => '' }), /is corrupt$/)

  fs.writeFileSync(manifestPath, '{nope')
  reject()
  fs.writeFileSync(manifestPath, '[]')
  reject()

  delete raw.version // pre-version manifest
  fs.writeFileSync(manifestPath, JSON.stringify(raw))
  reject()

  fs.writeFileSync(manifestPath, JSON.stringify({ ...raw, version: 1, files: [{ original: '/x' }] }))
  reject()
  fs.writeFileSync(manifestPath, JSON.stringify({ ...raw, version: 1, files: [{ original: '/x', saved: '/y', symlink: true }] }))
  reject()
  fs.writeFileSync(manifestPath, JSON.stringify({ ...raw, version: 1, launchd: [1] }))
  reject()
  assert.equal(fs.readFileSync(files.shim, 'utf8'), 'old claude shim\n') // nothing was touched
})

test('latest: newest backup manifest, null when none', () => {
  assert.equal(latest(), null)
  const files = setup(home)
  const one = create({ ts: '2026-10-01T1000' })
  one.save(files.shim)
  one.write()
  const two = create({ ts: '2026-10-02T0900' })
  two.save(files.plist)
  two.write()
  assert.equal(latest(), two.write())
})

const mk = (dir: string, ts: string, created: string, files: number) => {
  const b = create({ ts, dir, now: new Date(created) })
  const f = path.join(home, `f-${ts}`)
  fs.writeFileSync(f, 'x')
  Array.from({ length: files }).forEach(() => b.save(f))
  return b.write()
}

test('latest/list: foreign dirs, stray files and corrupt manifests are ignored', () => {
  const dir = path.join(home, 'bk')
  const real = mk(dir, '2026-10-02T1743', '2026-10-02T17:43:00Z', 1)
  fs.mkdirSync(path.join(dir, 'pencil-20261002-1323'), { recursive: true }) // sorts after "2026-…", no manifest
  fs.mkdirSync(path.join(dir, 'zz-bad'), { recursive: true })
  fs.writeFileSync(path.join(dir, 'zz-bad', 'manifest.json'), '{nope')
  fs.writeFileSync(path.join(dir, 'zz-file'), 'x')
  assert.equal(latest(dir), real)
  assert.deepEqual(list(dir).map((b) => b.ts), ['2026-10-02T1743'])
})

test('latest: empty manifests skipped, newest with entries chosen; --from overrides', () => {
  const dir = path.join(home, 'bk')
  const old = mk(dir, '2026-10-01T1000', '2026-10-01T10:00:00Z', 2)
  mk(dir, '2026-10-02T0900', '2026-10-02T09:00:00Z', 0) // re-run after uninstall: nothing to back up
  const mid = mk(dir, '2026-10-01T1500', '2026-10-01T15:00:00Z', 1)
  assert.equal(latest(dir), mid)
  assert.equal(latest(dir, fs, '2026-10-01T1000'), old)
  assert.equal(latest(dir, fs, '2026-10-02T0900'), path.join(dir, '2026-10-02T0900', 'manifest.json')) // explicit wins even if empty
  assert.equal(latest(dir, fs, 'nope'), null)
})

test('list: newest first by created, with one-line summaries', () => {
  const dir = path.join(home, 'bk')
  mk(dir, 'a-old', '2026-10-01T10:00:00Z', 2)
  mk(dir, 'b-new', '2026-10-02T09:00:00Z', 0)
  const all = list(dir)
  assert.deepEqual(all.map((b) => b.ts), ['b-new', 'a-old'])
  assert.equal(all[0]!.created, '2026-10-02T09:00:00.000Z')
  assert.equal(all[0]!.summary, 'nothing to restore')
  assert.equal(all[1]!.summary, '2 file(s)')
})
