import { test, beforeEach, afterEach } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, symlinkSync, chmodSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { stripVTControlCharacters as strip } from 'node:util'
import { default as doctor, diagnose, summary } from '../src/cli/doctor.ts'
import type { DiagnoseOpts } from '../src/cli/doctor.ts'
import type { CommandCtx, Config, DoctorCheck, Identity, ModelRules } from '../src/types.ts'

const keys = ['BARRITO_HOME', 'BARRITO_STATE', 'BARRITO_SHIMS', 'BARRITO_PLATFORM']
let prev: Record<string, string | undefined>
let tmp: string

beforeEach(() => {
  prev = Object.fromEntries(keys.map((k) => [k, process.env[k]]))
  tmp = mkdtempSync(path.join(os.tmpdir(), 'barrito-doctor-'))
  process.env.BARRITO_HOME = tmp
  process.env.BARRITO_STATE = path.join(tmp, 'state')
  process.env.BARRITO_SHIMS = path.join(tmp, 'shims')
  process.env.BARRITO_PLATFORM = 'darwin' // these suites assert launchd behavior; linux gets its own tests below
})

afterEach(() => {
  keys.forEach((k) => {
    if (prev[k] === undefined) delete process.env[k]
    else process.env[k] = prev[k]
  })
})

const glm = { id: 'zai/glm-5.3', name: 'GLM 5.3', type: 'language', tags: ['tool-use'], context_window: 200000, pricing: { input: '0.0000006', output: '0.000002' } }

const shims = (marker = true) => {
  const dir = process.env.BARRITO_SHIMS ?? ''
  mkdirSync(dir, { recursive: true })
  for (const bin of ['claude', 'codex', 'opencode', 'cursor-agent']) {
    writeFileSync(path.join(dir, bin), `#!/bin/sh\n${marker ? '# generated by barrito' : '# hand written'}\nexec real "$@"\n`)
  }
  // rtk and terminal-notifier are on PATH on a healthy machine — doctor probes for both
  writeFileSync(path.join(dir, 'rtk'), '#!/bin/sh\nexec real "$@"\n')
  writeFileSync(path.join(dir, 'terminal-notifier'), '#!/bin/sh\nexec real "$@"\n')
  chmodSync(path.join(dir, 'rtk'), 0o755)
  chmodSync(path.join(dir, 'terminal-notifier'), 0o755)
  rmSync(path.join(dir, 'agent'), { force: true })
  symlinkSync('cursor-agent', path.join(dir, 'agent'))
  // the real harness binaries, so doctor expects a shim for each (never depends on the host PATH)
  const real = realDir()
  mkdirSync(real, { recursive: true })
  for (const bin of ['claude', 'codex', 'opencode', 'cursor-agent']) {
    writeFileSync(path.join(real, bin), '#!/bin/sh\n')
    chmodSync(path.join(real, bin), 0o755)
  }
}

const realDir = () => path.join(process.env.BARRITO_HOME ?? '', 'realbin')

const identityDir = (name: string): string => {
  const dir = path.join(tmp, `claude-${name}`)
  mkdirSync(dir, { recursive: true })
  writeFileSync(path.join(dir, '.claude.json'), JSON.stringify({ oauthAccount: { accountUuid: 'x' } }))
  writeFileSync(path.join(dir, 'settings.json'), JSON.stringify({
    env: { ANTHROPIC_BASE_URL: 'http://127.0.0.1:4141' },
    modelPicker: { options: [{ model: 'claude-code/zai/glm-5.3', label: 'GLM 5.3', description: 'GLM 5.3' }] },
  }))
  return dir
}

const idn = (over: Partial<Identity> = {}): Identity => ({
  id: '',
  claude_config_dir: '',
  share_from: null,
  fallback: [],
  match: { remotes: [], paths: [] },
  keychain: {},
  ...over,
})

const rules = (over: Partial<ModelRules> = {}): ModelRules => ({
  include: [],
  exclude: [],
  require: [],
  max_input_price: null,
  pin: [],
  labels: {},
  suffix: {},
  agents: {},
  ...over,
})

const config = (): Config => ({
  port: 4141,
  default: 'personal',
  identities: {
    work: idn({
      id: 'work',
      claude_config_dir: identityDir('work'),
      keychain: { gateway: 'Vercel AI Gateway Work', cursor: 'Cursor Work' },
      fallback: ['zai/glm-5.3'],
    }),
  },
  models: rules({ include: ['zai/*'] }),
  graft: { roots: [], repos: [] },
  harness: {},
})

const cacheCatalog = (models = [glm]) => {
  mkdirSync(process.env.BARRITO_STATE ?? '', { recursive: true })
  writeFileSync(path.join(process.env.BARRITO_STATE ?? '', 'catalog.json'), JSON.stringify({ fetchedAt: Date.now(), data: models }))
}

const fetchOk = async () => ({ ok: true, status: 200, json: async () => ({ pid: 7085, uptime: 259200, identities: {}, spend: {} }) })

const execOk = () => {
  const uid = process.getuid?.()
  return (bin: string, args: string[]) => {
    if (bin === '/bin/launchctl' && args[1]?.endsWith('com.tybarho.claude-router')) throw Object.assign(new Error('not loaded'), { status: 44 })
    if (bin === '/bin/launchctl' && args[1]?.endsWith('dev.barrito.router')) return 'state = running\npid = 7085\n'
    throw new Error(`unexpected: ${bin} ${args.join(' ')}`)
  }
}

const keychainOk = { get: () => 'secret' }

const opts = (over: Partial<DiagnoseOpts> = {}): DiagnoseOpts => ({
  fetch: fetchOk,
  exec: execOk(),
  pathEnv: `${process.env.BARRITO_SHIMS}:${realDir()}:/usr/bin:/bin`,
  keychain: keychainOk,
  ...over,
})

const texts = (results: DoctorCheck[]): string[] => results.map((r) => `${r.level} ${r.text}`)

type TestCtx = CommandCtx & { printed: string[]; codes: number[] }

const mkCtx = (config: Config): TestCtx => {
  const out = { printed: [] as string[], codes: [] as number[] }
  return {
    printed: out.printed,
    codes: out.codes,
    config,
    print: (s: string) => { out.printed.push(s) },
    exit: (c: number) => { out.codes.push(c) },
  }
}

test('all checks pass', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts())
  assert.deepEqual(results.map((r) => r.level), Array(results.length).fill('ok'))
  assert.equal(texts(results).some((t) => t === 'ok router up 127.0.0.1:4141 (pid 7085, 3d)'), true)
  assert.equal(texts(results).some((t) => t === 'ok work: claude login · gateway key · cursor key'), true)
})

test('default prints ✓ lines and exits 0 when nothing fails', async () => {
  shims()
  cacheCatalog()
  const c = mkCtx(config())
  await doctor([], c, opts())
  assert.equal(c.codes.length, 0)
  // piped (non-TTY): one greppable line per check, no box-drawing, then the summary
  const checks = c.printed.slice(0, -1)
  assert.equal(checks.every((l) => l.startsWith('✓ ')), true)
  assert.match(c.printed.at(-1) ?? '', /^\d+ ok$/)
  assert.ok(!c.printed.some((l) => /[│◇└]/.test(l)))
})

const tty = { write: () => true, isTTY: true, columns: 200 }

test('terminal: checks render inside the spine with a one-line summary outro', async () => {
  shims()
  cacheCatalog()
  const c = mkCtx(config())
  await doctor([], c, opts({ term: tty, pathEnv: '/usr/bin:/bin' }))
  const lines = c.printed.map(strip)
  assert.equal(lines[0], 'barrito doctor')
  assert.equal(lines[2], '◇  Checks')
  const rows = lines.slice(3, -2)
  assert.ok(rows.length > 2)
  // every check is a tight spine row; a long one wraps under its text with a hanging indent
  assert.ok(rows.every((l) => /^│ {2}([✓!✗] | {2}\S)/.test(l)), lines.join('\n'))
  assert.equal(lines.at(-2), '│')
  assert.match(lines.at(-1) ?? '', /^└ {2}\d+ ok( · \d+ warnings?)? · \d+ failed$/)
  assert.deepEqual(c.codes, [1])
})

test('GITHUB_ACTIONS keeps plain lines even on a TTY', async () => {
  const c = mkCtx(config())
  await doctor([], c, opts({ term: tty, env: { GITHUB_ACTIONS: 'true', LANG: 'en_US.UTF-8' } }))
  assert.ok(!c.printed.some((l) => /[│◇└]/.test(l)))
  assert.match(c.printed.at(-1) ?? '', /^\d+ ok/)
})

test('NO_COLOR: ASCII marks and spine', async () => {
  shims()
  cacheCatalog()
  const c = mkCtx(config())
  await doctor([], c, opts({ term: tty, env: { NO_COLOR: '1', LANG: 'en_US.UTF-8' } }))
  assert.ok(!c.printed.some((l) => /[│◇└✓✗\u001b]/.test(l)), 'no unicode glyphs, no ANSI')
  assert.equal(c.printed[2], 'o  Checks')
  assert.ok(c.printed.slice(3, -2).every((l) => /^\| {2}(ok|!|x) /.test(l)))
  assert.match(c.printed.at(-1) ?? '', /^\+ {2}\d+ ok/)
})

test('summary pluralizes and drops empty buckets', () => {
  const r = (level: DoctorCheck['level']): DoctorCheck => ({ level, text: '' })
  assert.equal(summary([r('ok'), r('ok'), r('warn')]), '2 ok · 1 warning')
  assert.equal(summary([r('ok'), r('warn'), r('warn'), r('fail')]), '1 ok · 2 warnings · 1 failed')
})

test('shims dir not on PATH fails', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts({ pathEnv: '/usr/bin:/bin' }))
  const hit = results.find((r) => r.text.includes('not on PATH'))
  assert.equal(hit?.level, 'fail')
})

test('a real claude shadowing the shims fails', async () => {
  shims()
  cacheCatalog()
  const other = path.join(tmp, 'other')
  mkdirSync(other, { recursive: true })
  writeFileSync(path.join(other, 'claude'), '#!/bin/sh\n')
  chmodSync(path.join(other, 'claude'), 0o755)
  const results = await diagnose(config(), opts({ pathEnv: `${other}:${process.env.BARRITO_SHIMS}:${realDir()}:/usr/bin` }))
  const hit = results.find((r) => r.text.includes('shadowed'))
  assert.equal(hit?.level, 'fail')
})

test('a stale (non-barrito) shim fails with the fix', async () => {
  shims(false)
  cacheCatalog()
  const results = await diagnose(config(), opts())
  const hit = results.find((r) => r.text.startsWith('shim problems'))
  assert.equal(hit?.level, 'fail')
  assert.match(hit?.text ?? '', /claude \(not barrito-generated\)/)
})

test('a harness with no real binary on pathEnv is skipped — no shim expected, no fail', async () => {
  shims()
  cacheCatalog()
  // shims dir on PATH but no realbin dir: nothing is installed, so nothing is a missing shim
  const results = await diagnose(config(), opts({ pathEnv: `${process.env.BARRITO_SHIMS}:/usr/bin:/bin` }))
  assert.equal(results.some((r) => r.text.startsWith('shim problems')), false)
  assert.equal(results.some((r) => r.level === 'fail'), false)
})

test('legacy launchd service still loaded fails', async () => {
  shims()
  cacheCatalog()
  const exec = (bin: string, args: string[]) => {
    if (bin === '/bin/launchctl' && args[1]?.endsWith('com.tybarho.claude-router')) return 'state = running\npid = 99\n'
    return execOk()(bin, args)
  }
  const results = await diagnose(config(), opts({ exec }))
  const hit = results.find((r) => r.text.includes('legacy'))
  assert.equal(hit?.level, 'fail')
  assert.match(hit?.text ?? '', /launchctl bootout gui\/\d+\/com\.tybarho\.claude-router/)
})

test('missing gateway key fails the identity line', async () => {
  shims()
  cacheCatalog()
  const cfg = config()
  const results = await diagnose(cfg, opts({ keychain: { get: (s: string) => s === 'Vercel AI Gateway Work' ? null : 'secret' } }))
  const line = results.find((r) => r.text.startsWith('work:'))
  assert.equal(line?.level, 'fail')
  assert.match(line?.text ?? '', /gateway keychain "Vercel AI Gateway Work" missing/)
})

test('missing cursor key is a warning, not a failure', async () => {
  shims()
  cacheCatalog()
  const cfg = config()
  const results = await diagnose(cfg, opts({ keychain: { get: (s: string) => s === 'Cursor Work' ? null : 'secret' } }))
  const line = results.find((r) => r.text.startsWith('work:'))
  assert.equal(line?.level, 'warn')
  assert.match(line?.text ?? '', /cursor keychain "Cursor Work" missing/)
})

test('claude not logged in fails', async () => {
  shims()
  cacheCatalog()
  const cfg = config()
  rmSync(path.join(cfg.identities.work?.claude_config_dir ?? '', '.claude.json'))
  const results = await diagnose(cfg, opts())
  const line = results.find((r) => r.text.startsWith('work:'))
  assert.equal(line?.level, 'fail')
  assert.match(line?.text ?? '', /not logged in/)
})

test('wrong ANTHROPIC_BASE_URL fails', async () => {
  shims()
  cacheCatalog()
  const cfg = config()
  writeFileSync(path.join(cfg.identities.work?.claude_config_dir ?? '', 'settings.json'), JSON.stringify({ env: { ANTHROPIC_BASE_URL: 'http://localhost:9999' } }))
  const results = await diagnose(cfg, opts())
  const hit = results.find((r) => r.text.includes('ANTHROPIC_BASE_URL'))
  assert.equal(hit?.level, 'fail')
})

test('service loaded but not answering warns with kickstart fix', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts({ fetch: async () => ({ ok: false, status: 502, json: async () => ({}) }) }))
  const hit = results.find((r) => r.text.includes('not answering'))
  assert.equal(hit?.level, 'warn')
  assert.match(hit?.text ?? '', /launchctl kickstart -k gui\/\d+\/dev\.barrito\.router/)
})

test('router fully down fails', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts({
    fetch: async () => { throw new Error('refused') },
    exec: (bin: string, args: string[]) => {
      if (bin === 'ps') throw new Error('no ps')
      throw Object.assign(new Error('not loaded'), { status: 44 })
    },
  }))
  const hit = results.find((r) => r.text.includes('router not running'))
  assert.equal(hit?.level, 'fail')
})

test('no cached catalog warns', async () => {
  shims()
  const results = await diagnose(config(), opts())
  const hit = results.find((r) => r.text.includes('no gateway catalog cached'))
  assert.equal(hit?.level, 'warn')
})

test('missing catalog ids fail, new ones warn', async () => {
  shims()
  cacheCatalog([{ id: 'zai/glm-6.0', name: 'GLM 6', type: 'language', tags: ['tool-use'], context_window: 200000, pricing: { input: '0.0000006', output: '0.000002' } }])
  const results = await diagnose(config(), opts())
  assert.equal(results.find((r) => r.text.includes('models missing from gateway catalog'))?.level, 'fail')
  assert.match(results.find((r) => r.text.includes('models missing from gateway catalog'))?.text ?? '', /zai\/glm-5\.3/)
  assert.equal(results.find((r) => r.text.includes('new gateway models match your rules'))?.level, 'warn')
})

test('emdash started before the shims install warns to restart', async () => {
  shims()
  cacheCatalog()
  const exec = (bin: string, args: string[]) => {
    if (bin === 'ps' && args[0] === '-axo') return '   123 /Applications/emdash.app/Contents/MacOS/emdash\n  456 /usr/sbin/other\n'
    if (bin === 'ps' && args.includes('-p')) return 'Mon Jan  1 10:00:00 2024\n'
    return execOk()(bin, args)
  }
  const results = await diagnose(config(), opts({ exec }))
  const hit = results.find((r) => r.text.includes('restart emdash'))
  assert.equal(hit?.level, 'warn')
})

test('emdash started after the shims install is silent', async () => {
  shims()
  cacheCatalog()
  const exec = (bin: string, args: string[]) => {
    const future = new Date(Date.now() + 3600e3).toString()
    if (bin === 'ps' && args[0] === '-axo') return '   123 /Applications/emdash.app/Contents/MacOS/emdash\n'
    if (bin === 'ps' && args.includes('-p')) return `${future}\n`
    return execOk()(bin, args)
  }
  const results = await diagnose(config(), opts({ exec }))
  assert.equal(results.some((r) => r.text.includes('restart emdash')), false)
})

test('host restart warnings are deduped to one line per host, not per process', async () => {
  shims()
  cacheCatalog()
  const exec = (bin: string, args: string[]) => {
    if (bin === 'ps' && args[0] === '-axo') {
      return '   123 /Applications/emdash.app/Contents/MacOS/emdash\n  456 /Applications/emdash.app/Contents/MacOS/emdash\n  789 /Applications/Conductor.app/Contents/MacOS/conductor\n'
    }
    if (bin === 'ps' && args.includes('-p')) return 'Mon Jan  1 10:00:00 2024\n'
    return execOk()(bin, args)
  }
  const results = await diagnose(config(), opts({ exec }))
  assert.deepEqual(
    results.filter((r) => r.text.includes('started before the shims install')).map((r) => r.text),
    ['emdash started before the shims install → restart emdash', 'conductor started before the shims install → restart conductor'],
  )
})

test('any ✗ makes the command exit 1; --json dumps results and exits 1 too', async () => {
  shims()
  cacheCatalog([])
  const c = mkCtx(config())
  await doctor([], c, opts())
  assert.equal(c.printed.some((l) => l.startsWith('✗ ')), true)
  assert.deepEqual(c.codes, [1])

  const j = mkCtx(config())
  await doctor(['--json'], j, opts())
  const parsed = JSON.parse(j.printed.join(''))
  assert.equal(parsed.every((r: DoctorCheck) => ['ok', 'warn', 'fail'].includes(r.level)), true)
  assert.equal(parsed.some((r: DoctorCheck) => r.level === 'fail'), true)
  assert.deepEqual(j.codes, [1])
})

test('--json with every check passing exits 0', async () => {
  shims()
  cacheCatalog()
  const c = mkCtx(config())
  await doctor(['--json'], c, opts())
  assert.equal(JSON.parse(c.printed.join('')).every((r: DoctorCheck) => r.level === 'ok'), true)
  assert.deepEqual(c.codes, [])
})

// ── linux ─────────────────────────────────────────────────────────────────────

const execLinux = (over: { systemctl?: string; loginctl?: string } = {}) => (bin: string, args: string[]) => {
  if (bin === 'systemctl') return over.systemctl ?? 'ActiveState=active\nMainPID=7085\n'
  if (bin === 'loginctl') return over.loginctl ?? 'Linger=yes\n'
  if (bin === 'ps') throw new Error('no ps')
  throw new Error(`unexpected: ${bin} ${args.join(' ')}`)
}

const linuxOpts = (over: Partial<DiagnoseOpts> = {}): DiagnoseOpts => opts({
  exec: execLinux(),
  env: { USER: 'ty', SHELL: '/bin/bash' },
  keyring: () => true,
  ...over,
})

test('linux: rc PATH line + router via systemd; no legacy launchd line', async () => {
  process.env.BARRITO_PLATFORM = 'linux'
  shims()
  cacheCatalog()
  writeFileSync(path.join(tmp, '.bashrc'), 'export PATH="$HOME/.local/shims:$PATH"\n')
  const results = await diagnose(config(), linuxOpts())
  assert.equal(texts(results).includes('ok ~/.local/shims prepended in ~/.bashrc'), true)
  assert.equal(texts(results).some((t) => t === 'ok router up 127.0.0.1:4141 (pid 7085, 3d)'), true)
  assert.equal(texts(results).some((t) => t.includes('linger')), false)
  assert.equal(texts(results).some((t) => t.includes('legacy')), false)
  assert.equal(texts(results).some((t) => t.includes('secret-tool')), false)
})

test('linux: missing rc line fails with the exact fix; linger off and no keyring warn', async () => {
  process.env.BARRITO_PLATFORM = 'linux'
  shims()
  cacheCatalog()
  const results = await diagnose(config(), linuxOpts({
    exec: execLinux({ loginctl: 'Linger=no\n' }),
    keyring: () => false,
  }))
  const rc = results.find((r) => r.text.includes('not in ~/.bashrc'))
  assert.equal(rc?.level, 'fail')
  assert.match(rc?.text ?? '', /add 'export PATH="\$HOME\/\.local\/shims:\$PATH"'/)
  assert.equal(results.find((r) => r.text.includes('linger not enabled'))?.level, 'warn')
  assert.match(results.find((r) => r.text.includes('linger not enabled'))?.text ?? '', /loginctl enable-linger ty/)
  assert.equal(results.find((r) => r.text.includes('secret-tool unavailable'))?.level, 'warn')
})

test('linux: fish shell misses the rc line in conf.d, exact fix is fish_add_path', async () => {
  process.env.BARRITO_PLATFORM = 'linux'
  shims()
  cacheCatalog()
  const results = await diagnose(config(), linuxOpts({ env: { USER: 'ty', SHELL: '/usr/bin/fish' } }))
  const rc = results.find((r) => r.text.includes('not in ~/.config/fish/conf.d/barrito.fish'))
  assert.equal(rc?.level, 'fail')
  assert.match(rc?.text ?? '', /add 'fish_add_path -p ~\/\.local\/shims'/)
})

test('linux: service active but not answering warns with systemctl restart', async () => {
  process.env.BARRITO_PLATFORM = 'linux'
  shims()
  cacheCatalog()
  writeFileSync(path.join(tmp, '.bashrc'), 'export PATH="$HOME/.local/shims:$PATH"\n')
  const results = await diagnose(config(), linuxOpts({
    fetch: async () => ({ ok: false, status: 502, json: async () => ({}) }),
  }))
  const hit = results.find((r) => r.text.includes('not answering'))
  assert.equal(hit?.level, 'warn')
  assert.match(hit?.text ?? '', /systemctl --user restart barrito/)
})

test('linux: detached router (no systemd) answering on /health is up', async () => {
  process.env.BARRITO_PLATFORM = 'linux'
  shims()
  cacheCatalog()
  writeFileSync(path.join(tmp, '.bashrc'), 'export PATH="$HOME/.local/shims:$PATH"\n')
  const results = await diagnose(config(), linuxOpts({
    exec: (bin, args) => {
      if (bin === 'systemctl') throw new Error('Failed to connect to bus')
      if (bin === 'ps') throw new Error('no ps')
      throw new Error(`unexpected: ${bin} ${args.join(' ')}`)
    },
  }))
  assert.equal(texts(results).some((t) => t === 'ok router up 127.0.0.1:4141 (pid 7085, 3d)'), true)
})

// ── keyring refs ──────────────────────────────────────────────────────────────

test('env: and file: gateway refs report by kind', async () => {
  shims()
  cacheCatalog()
  const cfg = config()
  cfg.identities.work!.keychain = { gateway: 'env:GW_KEY' }
  const ok = await diagnose(cfg, opts({ keychain: { get: (r) => r === 'env:GW_KEY' ? 'x' : null } }))
  assert.equal(texts(ok).some((t) => t === 'ok work: claude login · gateway key'), true)
  const missing = await diagnose(cfg, opts({ keychain: { get: () => null } }))
  assert.equal(texts(missing).some((t) => t === 'fail work: claude login · gateway env:GW_KEY missing'), true)
})

test('a keyring get that throws (no keyring) is a warning, not a crash', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts({ keychain: { get: () => { throw new Error('Cannot autolaunch D-Bus') } } }))
  const line = results.find((r) => r.text.startsWith('work:'))
  assert.equal(line?.level, 'warn')
  assert.match(line?.text ?? '', /unreadable — no keyring/)
})

// the macOS ACL prompt ("user interaction is not allowed" / user canceled) has its own fix
test('a keyring get denied by keychain access-control warns with the own fix', async () => {
  shims()
  cacheCatalog()
  const denied = { get: () => { throw new Error('security: SecKeychainItemCopyAttributesAndData: User interaction is not allowed.') } }
  const results = await diagnose(config(), opts({ keychain: denied }))
  const line = results.find((r) => r.text.startsWith('work:'))
  assert.equal(line?.level, 'warn')
  assert.match(line?.text ?? '', /gateway keychain "Vercel AI Gateway Work" prompts for keychain access — barrito keychain own/)
  assert.match(line?.text ?? '', /cursor keychain "Cursor Work" prompts for keychain access — barrito keychain own/)
  assert.ok(!line?.text.includes('unreadable — no keyring'))
})

// ── CI (GITHUB_ACTIONS) ───────────────────────────────────────────────────────

test('CI: BARRITO_* env + router health + env: refs; no service/host/identity lines', async () => {
  shims()
  cacheCatalog()
  const cfg = config()
  cfg.identities.work!.keychain = { gateway: 'env:AI_GATEWAY_API_KEY' }
  const results = await diagnose(cfg, opts({
    env: { GITHUB_ACTIONS: 'true', BARRITO_PORT: '4141', BARRITO_IDENTITY: 'ci', AI_GATEWAY_API_KEY: 'x' },
  }))
  const joined = texts(results)
  assert.equal(joined.includes('ok BARRITO_PORT=4141'), true)
  assert.equal(joined.includes('ok BARRITO_IDENTITY=ci'), true)
  assert.equal(joined.includes('ok router up 127.0.0.1:4141'), true)
  assert.equal(joined.includes('ok work: gateway env:AI_GATEWAY_API_KEY'), true)
  assert.equal(joined.some((t) => t.includes('claude login')), false)
  assert.equal(joined.some((t) => t.includes('legacy')), false)
  assert.equal(joined.some((t) => t.includes('emdash')), false)
})

test('CI: keyring-name ref fails with the env:/file: fix; unset env ref fails; unset BARRITO_* warns', async () => {
  shims()
  cacheCatalog()
  const keyring = await diagnose(config(), opts({ env: { GITHUB_ACTIONS: 'true' } }))
  assert.match(
    texts(keyring).find((t) => t.includes('Vercel AI Gateway Work')) ?? '',
    /fail work: gateway ref "Vercel AI Gateway Work" is a keyring name — CI has no keyring/,
  )
  assert.equal(texts(keyring).includes('warn BARRITO_PORT not set — the router falls back to config port 4141; barrito ci exports it'), true)
  assert.equal(texts(keyring).includes('warn BARRITO_IDENTITY not set — everything routes to "personal" (barrito ci --identity …)'), true)

  const cfg = config()
  cfg.identities.work!.keychain = { gateway: 'env:MISSING_VAR' }
  const unset = await diagnose(cfg, opts({ env: { GITHUB_ACTIONS: 'true' } }))
  assert.equal(texts(unset).includes('fail work: env:MISSING_VAR not set — add it to the step env'), true)
})

test('CI: router not answering fails', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts({
    fetch: async () => { throw new Error('refused') },
    env: { GITHUB_ACTIONS: 'true' },
  }))
  assert.equal(results.find((r) => r.text.includes('router not answering'))?.level, 'fail')
})

test('CI: file: gateway ref is checked for readability, not just existence', async () => {
  shims()
  cacheCatalog()
  const cfg = config()
  cfg.identities.work!.keychain = { gateway: 'file:/nope/gw.key' }
  const missing = await diagnose(cfg, opts({ env: { GITHUB_ACTIONS: 'true' } }))
  assert.equal(texts(missing).includes('fail work: file:/nope/gw.key not readable'), true)

  const key = path.join(tmp, 'gw.key')
  writeFileSync(key, 'secret')
  cfg.identities.work!.keychain = { gateway: `file:${key}` }
  const ok = await diagnose(cfg, opts({ env: { GITHUB_ACTIONS: 'true' } }))
  assert.equal(texts(ok).includes(`ok work: gateway file:${key}`), true)
})

// ── transforms / rtk ──────────────────────────────────────────────────────────

test('rtk enabled (default) but not on PATH warns with the brew fix', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts({ pathEnv: '/usr/bin:/bin' }))
  const hit = results.find((r) => r.text.includes('rtk enabled but not on PATH'))
  assert.equal(hit?.level, 'warn')
  assert.match(hit?.text ?? '', /brew install rtk/)
})

test('rtk disabled for every identity → no rtk line', async () => {
  shims()
  cacheCatalog()
  const cfg = config()
  cfg.transforms = { rtk: false, caveman: 'off' }
  const results = await diagnose(cfg, opts())
  assert.equal(results.some((r) => r.text.includes('rtk enabled but not on PATH')), false)
})

test('a per-identity override enabling rtk warns even with the global default off', async () => {
  shims()
  cacheCatalog()
  const cfg = config()
  cfg.transforms = { rtk: false, caveman: 'off' }
  cfg.identities.work!.transforms = { rtk: true }
  const results = await diagnose(cfg, opts({ pathEnv: '/usr/bin:/bin' }))
  assert.equal(results.find((r) => r.text.includes('rtk enabled but not on PATH'))?.level, 'warn')
})

test('rtk on PATH → no line', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts())
  assert.equal(results.some((r) => r.text.includes('rtk enabled but not on PATH')), false)
})

// ── terminal-notifier (macOS notification icon) ───────────────────────────────

test('macOS without terminal-notifier warns with the brew fix', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts({ pathEnv: '/usr/bin:/bin' }))
  const hit = results.find((r) => r.text.includes('notifications use osascript'))
  assert.equal(hit?.level, 'warn')
  assert.match(hit?.text ?? '', /brew install terminal-notifier/)
})

test('terminal-notifier on PATH → no line', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts())
  assert.equal(results.some((r) => r.text.includes('notifications use osascript')), false)
})

test('linux never warns about terminal-notifier', async () => {
  shims()
  cacheCatalog()
  process.env.BARRITO_PLATFORM = 'linux'
  try {
    const results = await diagnose(config(), opts({ pathEnv: '/usr/bin:/bin' }))
    assert.equal(results.some((r) => r.text.includes('terminal-notifier')), false)
  } finally {
    process.env.BARRITO_PLATFORM = 'darwin'
  }
})

test('CI skips the terminal-notifier check', async () => {
  shims()
  cacheCatalog()
  const results = await diagnose(config(), opts({ env: { GITHUB_ACTIONS: 'true', BARRITO_PORT: '4141', BARRITO_IDENTITY: 'ci', AI_GATEWAY_API_KEY: 'x' } }))
  assert.equal(results.some((r) => r.text.includes('terminal-notifier')), false)
})
