import { test, describe } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import { join, dirname, resolve as resolvePath } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync, execFileSync } from 'node:child_process'
import type { TestContext } from 'node:test'
import shim from '../src/cli/shim.ts'
import which from '../src/cli/which.ts'
import env from '../src/cli/env.ts'
import exec from '../src/cli/exec.ts'
import type { CommandCtx, Config } from '../src/types.ts'

const root = resolvePath(dirname(fileURLToPath(import.meta.url)), '..')
const MARKER = 'generated by barrito'

const tmp = () => fs.mkdtempSync(join(os.tmpdir(), 'barrito-shim-'))

const ctx = (config: Config): CommandCtx & { lines: string[]; errors: string[]; code: number | null } => {
  const lines: string[] = []
  const errors: string[] = []
  let code: number | null = null
  return {
    config,
    lines,
    errors,
    get code() { return code },
    print: (line: string) => { lines.push(line) },
    exit: (status: number) => { code = status },
  }
}

const config: Config = {
  default: 'work',
  port: 4141,
  identities: {
    work: {
      id: 'work',
      claude_config_dir: "/tmp/barrito-it's/.claude",
      share_from: null,
      fallback: [],
      match: { remotes: [], paths: [] },
      keychain: { cursor: 'Cursor Work' },
    },
  },
  models: { include: [], exclude: [], require: [], max_input_price: null, pin: [], labels: {}, agents: {} },
  graft: { roots: [], repos: [] },
  harness: { mybot: { bin: 'mybot', env: { OPENAI_BASE_URL: '{gateway}/v1', OPENAI_API_KEY: '{handle}' } } },
}

const withEnv = (t: TestContext, vars: Record<string, string | undefined>, fn: () => Promise<void>): Promise<void> => {
  const saved: Record<string, string | undefined> = {}
  for (const k of Object.keys(vars)) {
    saved[k] = process.env[k]
    if (vars[k] === undefined) delete process.env[k]
    else process.env[k] = vars[k]
  }
  t.after(() => {
    for (const k of Object.keys(saved)) {
      if (saved[k] === undefined) delete process.env[k]
      else process.env[k] = saved[k]
    }
  })
  return fn()
}

const stubBin = (dir: string, name: string, body = '#!/usr/bin/env bash\ntrue\n'): string => {
  fs.mkdirSync(dir, { recursive: true })
  const file = join(dir, name)
  fs.writeFileSync(file, `#!/usr/bin/env bash\n${body}\n`)
  fs.chmodSync(file, 0o755)
  return file
}

const baked = (): string => `${JSON.stringify(process.execPath)} ${JSON.stringify(fs.realpathSync(process.argv[1]!))}`

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

describe('barrito shim (unit)', () => {
  test('writes exec-able marker files with baked paths + --self, and alias symlinks', async (t) => {
    const dir = tmp()
    t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
    const c = ctx(config)
    await shim(['claude', 'cursor-agent', 'mybot', '--dir', dir], c)
    assert.equal(c.code, null)
    for (const name of ['claude', 'cursor-agent', 'mybot']) {
      const body = fs.readFileSync(join(dir, name), 'utf8')
      assert.ok(body.includes(MARKER))
      assert.ok(body.includes(`eval "$(${baked()} env --shell --harness ${name} --self "$0")" || exit $?`), body)
      assert.ok(body.includes('[ -n "${BARRITO_REAL_BIN:-}" ] || exit 127'))
      assert.ok(body.includes('exec "$BARRITO_REAL_BIN" "$@"'))
      assert.equal(fs.statSync(join(dir, name)).mode & 0o111, 0o111)
    }
    assert.equal(fs.readlinkSync(join(dir, 'agent')), 'cursor-agent')
  })

  test('no args = all builtins + config harnesses', async (t) => {
    const dir = tmp()
    t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
    const c = ctx(config)
    await shim(['--dir', dir], c)
    for (const name of ['claude', 'codex', 'opencode', 'cursor-agent', 'mybot', 'agent']) {
      assert.ok(fs.existsSync(join(dir, name)), name)
    }
  })

  test('regenerating a marked file is fine', async (t) => {
    const dir = tmp()
    t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
    await shim(['claude', '--dir', dir], ctx(config))
    const c = ctx(config)
    await shim(['claude', '--dir', dir], c)
    assert.equal(c.code, null)
  })

  test('refuses to overwrite foreign files, lists them, changes nothing', async (t) => {
    const dir = tmp()
    t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
    fs.writeFileSync(join(dir, 'claude'), 'my hand-written shim\n')
    const err = t.mock.method(console, 'error', () => {})
    const c = ctx(config)
    await shim(['claude', '--dir', dir], c)
    assert.equal(c.code, 1)
    assert.equal(fs.readFileSync(join(dir, 'claude'), 'utf8'), 'my hand-written shim\n')
    assert.ok(err.mock.calls.some((call) => String(call.arguments[0]).includes(join(dir, 'claude'))))
  })

  test('a foreign file at an alias path is also protected', async (t) => {
    const dir = tmp()
    t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
    fs.writeFileSync(join(dir, 'agent'), '#!/bin/sh\nmy agent wrapper\n')
    t.mock.method(console, 'error', () => {})
    const c = ctx(config)
    await shim(['cursor-agent', '--dir', dir], c)
    assert.equal(c.code, 1)
    assert.ok(!fs.existsSync(join(dir, 'cursor-agent')))
  })

  test('--force overwrites foreign files', async (t) => {
    const dir = tmp()
    t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
    fs.writeFileSync(join(dir, 'claude'), 'custom\n')
    const c = ctx(config)
    await shim(['claude', '--dir', dir, '--force'], c)
    assert.equal(c.code, null)
    assert.ok(fs.readFileSync(join(dir, 'claude'), 'utf8').includes(MARKER))
  })

  test('unknown harness → exit 2', async () => {
    const c = ctx(config)
    await shim(['nope', '--dir', tmp()], c)
    assert.equal(c.code, 2)
  })
})

describe('barrito which (unit)', () => {
  test('env rule wording', async (t) => {
    await withEnv(t, { BARRITO_IDENTITY: 'work' }, async () => {
      const c = ctx(config)
      await which([], c)
      assert.deepEqual(c.lines, ['work  ← env BARRITO_IDENTITY'])
    })
  })

  test('--json', async (t) => {
    await withEnv(t, { BARRITO_IDENTITY: 'work' }, async () => {
      const c = ctx(config)
      await which(['--json'], c)
      assert.deepEqual(JSON.parse(c.lines[0]!), { id: 'work', rule: 'env', detail: 'BARRITO_IDENTITY' })
    })
  })

  test('default rule wording for a plain non-repo dir', async (t) => {
    await withEnv(t, { BARRITO_IDENTITY: undefined, GIT_CONFIG_GLOBAL: '/dev/null', GIT_CONFIG_SYSTEM: '/dev/null' }, async () => {
      const c = ctx(config)
      await which([tmp()], c)
      assert.equal(c.lines[0], 'work  ← default')
    })
  })
})

describe('barrito env (unit)', () => {
  test('prints the resolved env + real bin', async (t) => {
    const bin = stubBin(tmp(), 'claude')
    await withEnv(t, { BARRITO_IDENTITY: 'work', PATH: `${dirname(bin)}:/usr/bin:/bin`, BARRITO_SHIMS: tmp() }, async () => {
      const c = ctx(config)
      await env([], c)
      assert.equal(c.code, null)
      const out = c.lines.join('\n').split('\n')
      assert.ok(out.includes('ANTHROPIC_BASE_URL=http://127.0.0.1:4141'))
      assert.ok(out.includes(`CLAUDE_CONFIG_DIR=${config.identities.work!.claude_config_dir}`))
      assert.ok(out.includes('ANTHROPIC_CUSTOM_HEADERS=x-barrito-identity: work'))
      assert.ok(out.includes('BARRITO_IDENTITY=work'))
      assert.ok(out.includes(`BARRITO_REAL_BIN=${fs.realpathSync(bin)}`))
    })
  })

  test('--shell emits quoted export lines, incl. single-quote escaping', async (t) => {
    const bin = stubBin(tmp(), 'claude')
    await withEnv(t, { BARRITO_IDENTITY: 'work', PATH: `${dirname(bin)}:/usr/bin:/bin`, BARRITO_SHIMS: tmp() }, async () => {
      const c = ctx(config)
      await env(['--shell'], c)
      const out = c.lines.join('\n').split('\n')
      assert.ok(out.includes("export CLAUDE_CONFIG_DIR='/tmp/barrito-it'\\''s/.claude'"), out.join('\n'))
      assert.ok(out.some((l) => l.startsWith('export BARRITO_REAL_BIN=')))
      assert.ok(out.every((l) => /^export [A-Z_]+='/.test(l)))
    })
  })

  test('--harness codex expands gateway templates', async (t) => {
    const bin = stubBin(tmp(), 'codex')
    await withEnv(t, { BARRITO_IDENTITY: 'work', PATH: `${dirname(bin)}:/usr/bin:/bin`, BARRITO_SHIMS: tmp() }, async () => {
      const c = ctx(config)
      await env(['--shell', '--harness', 'codex'], c)
      const out = c.lines.join('\n').split('\n')
      assert.ok(out.includes("export OPENAI_BASE_URL='http://127.0.0.1:4141/gateway/v1'"))
      assert.ok(out.includes("export OPENAI_API_KEY='barrito:work'"))
    })
  })

  test('--self keeps realBin from ever returning the shim itself', async (t) => {
    const bin = stubBin(tmp(), 'claude')
    const self = stubBin(tmp(), 'claude', 'echo nope') // no marker, outside the shims dir
    await withEnv(t, { BARRITO_IDENTITY: 'work', PATH: `${dirname(self)}:${dirname(bin)}`, BARRITO_SHIMS: tmp() }, async () => {
      const c = ctx(config)
      await env(['--shell', '--self', self], c)
      assert.equal(c.code, null)
      const out = c.lines.join('\n').split('\n')
      assert.ok(out.includes(`export BARRITO_REAL_BIN='${fs.realpathSync(bin)}'`), out.join('\n'))
    })
  })

  test('unknown BARRITO_IDENTITY → stderr + exit 2; --shell also prints `exit 2` for the eval', async (t) => {
    const err = t.mock.method(console, 'error', () => {})
    const bin = stubBin(tmp(), 'claude')
    await withEnv(t, { BARRITO_IDENTITY: 'ghost', PATH: `${dirname(bin)}:/usr/bin:/bin`, BARRITO_SHIMS: tmp() }, async () => {
      const c = ctx(config)
      await env([], c)
      assert.equal(c.code, 2)
      assert.equal(c.lines.length, 0)

      const shell = ctx(config)
      await env(['--shell'], shell)
      assert.equal(shell.code, 2)
      assert.deepEqual(shell.lines, ['exit 2'])
      assert.ok(err.mock.calls.some((call) => String(call.arguments[0]).includes('unknown identity "ghost" — run barrito doctor')))
    })
  })

  test('identity missing claude_config_dir → unknown identity error, never exports "undefined"', async (t) => {
    const err = t.mock.method(console, 'error', () => {})
    const bin = stubBin(tmp(), 'claude')
    const broken = { ...config, identities: { work: { ...config.identities.work!, claude_config_dir: '' } } }
    await withEnv(t, { BARRITO_IDENTITY: 'work', PATH: `${dirname(bin)}:/usr/bin:/bin`, BARRITO_SHIMS: tmp() }, async () => {
      const c = ctx(broken)
      await env([], c)
      assert.equal(c.code, 2)
      assert.equal(c.lines.length, 0)
      assert.ok(err.mock.calls.some((call) => String(call.arguments[0]).includes('unknown identity "work"')))
    })
  })

  test('BARRITO_DEBUG=1 prints identity + redacted var values to stderr', async (t) => {
    const err = t.mock.method(console, 'error', () => {})
    const bin = stubBin(tmp(), 'claude')
    await withEnv(t, {
      BARRITO_IDENTITY: 'work',
      BARRITO_DEBUG: '1',
      PATH: `${dirname(bin)}:/usr/bin:/bin`,
      BARRITO_SHIMS: tmp(),
    }, async () => {
      const c = ctx(config)
      await env([], c)
      const logged = err.mock.calls.map((call) => String(call.arguments[0])).join('\n')
      assert.ok(logged.includes('work ← env BARRITO_IDENTITY'))
      assert.ok(logged.includes('ANTHROPIC_BASE_URL=<redacted:'))
      assert.ok(!logged.includes('http://127.0.0.1:4141'))
    })
  })

  test('missing real binary → stderr + exit 127, and `exit 127` on stdout in shell mode', async (t) => {
    const err = t.mock.method(console, 'error', () => {})
    await withEnv(t, { BARRITO_IDENTITY: 'work', PATH: '/nonexistent-barrito:/usr/bin:/bin', BARRITO_SHIMS: tmp() }, async () => {
      const c = ctx(config)
      await env([], c)
      assert.equal(c.code, 127)
      assert.equal(c.lines.length, 0)

      const shell = ctx(config)
      await env(['--shell'], shell)
      assert.equal(shell.code, 127)
      assert.deepEqual(shell.lines, ['exit 127'])
      assert.ok(err.mock.calls.some((call) => /no real "claude"/.test(String(call.arguments[0]))))
    })
  })

  test('unknown harness → exit 2 (+ `exit 2` in shell mode)', async (t) => {
    t.mock.method(console, 'error', () => {})
    await withEnv(t, { BARRITO_IDENTITY: 'work' }, async () => {
      const c = ctx(config)
      await env(['--harness', 'nope'], c)
      assert.equal(c.code, 2)

      const shell = ctx(config)
      await env(['--shell', '--harness', 'nope'], shell)
      assert.deepEqual(shell.lines, ['exit 2'])
    })
  })
})

describe('barrito exec (unit)', () => {
  test('runs the real bin with identity env; everything after the bin passes through untouched', async (t) => {
    const capture = join(tmp(), 'capture')
    const bin = stubBin(tmp(), 'claude', `printf '%s' "id=$BARRITO_IDENTITY base=$ANTHROPIC_BASE_URL args=$*" > "$CAPTURE"\nexit 42`)
    const path = `${dirname(bin)}:/usr/bin:/bin` // stub's `#!/usr/bin/env bash` needs env+bash on PATH
    await withEnv(t, { BARRITO_IDENTITY: 'work', PATH: path, BARRITO_SHIMS: tmp(), CAPTURE: capture }, async () => {
      const c = ctx(config)
      await exec(['claude', '-p', '--flag', 'a b', '--', 'x'], c)
      assert.equal(c.code, 42)
      assert.equal(
        fs.readFileSync(capture, 'utf8'),
        'id=work base=http://127.0.0.1:4141 args=-p --flag a b -- x',
      )
    })
  })

  test('a single leading -- after the bin is stripped, the rest passes through', async (t) => {
    const capture = join(tmp(), 'capture-dashdash')
    const bin = stubBin(tmp(), 'claude', `printf '%s' "id=$BARRITO_IDENTITY args=$*" > "$CAPTURE"\nexit 0`)
    const path = `${dirname(bin)}:/usr/bin:/bin` // stub's `#!/usr/bin/env bash` needs env+bash on PATH
    await withEnv(t, { BARRITO_IDENTITY: 'work', PATH: path, BARRITO_SHIMS: tmp(), CAPTURE: capture }, async () => {
      const c = ctx(config)
      await exec(['claude', '--', '-p', 'x', '--flag'], c)
      assert.equal(c.code, 0)
      assert.equal(fs.readFileSync(capture, 'utf8'), 'id=work args=-p x --flag')
    })
  })

  test('unknown BARRITO_IDENTITY → exit 2', async (t) => {
    t.mock.method(console, 'error', () => {})
    const bin = stubBin(tmp(), 'claude')
    await withEnv(t, { BARRITO_IDENTITY: 'ghost', PATH: `${dirname(bin)}:/usr/bin:/bin`, BARRITO_SHIMS: tmp() }, async () => {
      const c = ctx(config)
      await exec(['claude'], c)
      assert.equal(c.code, 2)
    })
  })

  test('missing bin → exit 127', async (t) => {
    t.mock.method(console, 'error', () => {})
    await withEnv(t, { BARRITO_IDENTITY: 'work', PATH: '/nonexistent-barrito:/usr/bin:/bin', BARRITO_SHIMS: tmp() }, async () => {
      const c = ctx(config)
      await exec(['claude'], c)
      assert.equal(c.code, 127)
    })
  })

  test('no bin → usage + exit 2', async () => {
    const c = ctx(config)
    await exec([], c)
    assert.equal(c.code, 2)
  })
})

describe('e2e: generated shim end-to-end (scrubbed env, real git, no real HOME/keychain)', () => {
  const ready = fs.existsSync(join(root, 'src/config.ts')) && fs.existsSync(join(root, 'node_modules/smol-toml'))

  test('shim → barrito env → stub claude with work identity; finds the real bin, never itself; zero git spawns warm', { skip: !ready && 'waiting on src/config.js (workstream D)' }, async (t) => {
    const dir = tmp()
    t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
    const { shims, bin, state, home, repo, gitCount } = setupE2E(dir)

    // env -i equivalent: PATH has the shims dir first and NO node/barrito dir — the baked paths carry those
    const clean = {
      PATH: [shims, dirname(gitCount.wrapper), bin, '/usr/bin', '/bin'].join(':'),
      HOME: home,
      BARRITO_HOME: home,
      BARRITO_CONFIG: join(dir, 'config.toml'),
      BARRITO_STATE: state,
      BARRITO_SHIMS: shims,
      BARRITO_GIT_COUNT: gitCount.file,
      GIT_CONFIG_GLOBAL: '/dev/null',
      GIT_CONFIG_SYSTEM: '/dev/null',
      TMPDIR: os.tmpdir(),
    }

    const barritoJs = join(root, 'bin', 'barrito.ts')
    const gen = spawnSync(process.execPath, [barritoJs, 'shim', 'claude', '--dir', shims], { encoding: 'utf8', env: clean })
    assert.equal(gen.status, 0, gen.stderr)
    const shimBody = fs.readFileSync(join(shims, 'claude'), 'utf8')
    assert.ok(shimBody.includes(`eval "$(${JSON.stringify(process.execPath)} ${JSON.stringify(fs.realpathSync(barritoJs))} env --shell --harness claude --self "$0")"`), shimBody)

    const reads = () => {
      try { return Number(fs.readFileSync(gitCount.file, 'utf8').trim()) } catch { return 0 }
    }
    const out = (r: { stdout: string }): Record<string, string> => Object.fromEntries(r.stdout.trim().split('\n').map((l: string) => l.split('=')))

    const before = reads()
    const cold = spawnSync('claude', [], { encoding: 'utf8', cwd: repo, env: clean, shell: true }) // resolves via PATH
    assert.equal(cold.status, 0, cold.stderr)
    const coldSpawns = reads() - before
    assert.equal(coldSpawns, 3, `cold run should make exactly 3 git spawns (top, remote, commondir), made ${coldSpawns}`)
    const coldEnv = out(cold)
    assert.equal(coldEnv.BASE, 'http://127.0.0.1:4141')
    assert.equal(coldEnv.CFG, join(home, '.claude-work'))
    assert.equal(coldEnv.HDR, 'x-barrito-identity: work')
    assert.equal(coldEnv.ID, 'work')
    assert.equal(coldEnv.REAL, fs.realpathSync(join(bin, 'claude'))) // the stub, never the shim

    const beforeWarm = reads()
    const warm = spawnSync('claude', [], { encoding: 'utf8', cwd: repo, env: clean, shell: true })
    assert.equal(warm.status, 0, warm.stderr)
    assert.equal(reads() - beforeWarm, 0, 'warm run must make zero git spawns (cache hit, graft served from cache)')
    assert.deepEqual(out(warm), coldEnv)

    const cache: unknown = JSON.parse(fs.readFileSync(join(state, 'which.json'), 'utf8'))
    assert.ok(isRecord(cache))
    assert.ok(isRecord(cache.repos))
    assert.ok(isRecord(cache.dirs))
    const entry = cache.repos[String(cache.dirs[fs.realpathSync(repo)])]
    assert.ok(isRecord(entry))
    const result = entry.result
    assert.ok(isRecord(result))
    assert.equal(result.id, 'work')
    assert.equal(result.rule, 'remote')
    assert.equal(entry.configFile, join(fs.realpathSync(repo), '.git', 'config'))

    const whichRun = spawnSync(process.execPath, [barritoJs, 'which'], { encoding: 'utf8', cwd: repo, env: clean })
    assert.match(whichRun.stdout.trim(), /^work  ← remote github\.com\/acme\/x$/)
  })
})

const setupE2E = (dir: string) => {
  const shims = join(dir, 'shims')
  const bin = join(dir, 'bin')
  const state = join(dir, 'state')
  const home = join(dir, 'home')
  const repo = join(dir, 'repo')
  for (const d of [bin, state, home, repo]) fs.mkdirSync(d, { recursive: true })

  stubBin(bin, 'claude', [
    'echo "BASE=$ANTHROPIC_BASE_URL"',
    'echo "CFG=$CLAUDE_CONFIG_DIR"',
    'echo "HDR=$ANTHROPIC_CUSTOM_HEADERS"',
    'echo "ID=$BARRITO_IDENTITY"',
    'echo "REAL=$BARRITO_REAL_BIN"',
  ].join('\n'))

  // PATH git wrapper that counts spawns, then forwards to the real git
  const gitDir = join(dir, 'gitwrap')
  const gitCount = { file: join(dir, 'git-count'), wrapper: stubBin(gitDir, 'git', `c=$(cat "$BARRITO_GIT_COUNT" 2>/dev/null || echo 0)\necho $((c + 1)) > "$BARRITO_GIT_COUNT"\nexec "${spawnSync('which', ['git'], { encoding: 'utf8' }).stdout.trim()}" "$@"`) }

  const gitEnv = { ...process.env, HOME: home, GIT_CONFIG_GLOBAL: '/dev/null', GIT_CONFIG_SYSTEM: '/dev/null' }
  execFileSync('git', ['init', '-q', repo], { env: gitEnv })
  execFileSync('git', ['-C', repo, 'remote', 'add', 'origin', 'git@github.com:acme/x.git'], { env: gitEnv })

  fs.writeFileSync(join(dir, 'config.toml'), `\
port = 4141
default = "personal"

[identities.work]
claude_config_dir = "${join(home, '.claude-work')}"

[identities.work.match]
remotes = ["github.com/acme/*"]

[identities.personal]
claude_config_dir = "${join(home, '.claude-personal')}"

[identities.personal.match]
remotes = ["github.com/you/*"]
`)
  return { shims, bin, state, home, repo, gitCount }
}
