import { parseArgs } from 'node:util'
import pc from 'picocolors'
import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import type { ExecFileSyncOptions } from 'node:child_process'
import { paths, home, expand, platform } from '../paths.ts'
import * as service from '../service/index.ts'
import * as launchd from '../service/launchd.ts'
import { unit } from '../service/systemd.ts'
import * as keychain from '../keychain/index.ts'
import { available as linuxKeyring } from '../keychain/linux.ts'
import * as catalog from '../catalog.ts'
import { builtins, find, realBin } from '../harnesses.ts'
import { read as readSettings } from '../settings.ts'
import { rcOf } from '../detect.ts'
import { base, fetchJson, nudges, parse as parseStatus, port } from './status.ts'
import { account } from '../claude.ts'
import type { CommandCtx, Config, DoctorCheck, Exec, FetchJson, Identity, Keychain, Settings } from '../types.ts'

const MARKER = 'generated by barrito'

export interface DiagnoseOpts {
  fetch?: FetchJson
  exec?: Exec
  pathEnv?: string
  keychain?: Keychain
  settings?: { read: Settings['read'] }
  env?: Record<string, string | undefined>
  keyring?: (o: { exec?: Exec }) => boolean
}

const real = (d: string): string | null => {
  try { return fs.realpathSync(d) } catch { return null }
}
const xok = (f: string): boolean => {
  try { fs.accessSync(f, fs.constants.X_OK); return true } catch { return false }
}

const human = (ms: number): string => {
  const s = Math.floor(ms / 1000)
  if (s < 60) return `${s}s`
  if (s < 3600) return `${Math.floor(s / 60)}m`
  if (s < 86400) return `${Math.floor(s / 3600)}h`
  return `${Math.floor(s / 86400)}d`
}

const shimsFirst = (pathEnv: string | undefined): DoctorCheck => {
  const shims = real(paths.shims) ?? paths.shims
  const dirs = (pathEnv ?? '').split(':').filter(Boolean).map((d) => real(d) ?? d)
  const at = dirs.indexOf(shims)
  if (at === -1) return { level: 'fail', text: `${paths.shims} not on PATH — add 'export PATH=${paths.shims}:$PATH' to your shell rc` }
  if (dirs.slice(0, at).some((d) => xok(path.join(d, 'claude')))) {
    return { level: 'fail', text: `${paths.shims} is shadowed by a real claude earlier on PATH — put the shims dir first` }
  }
  return { level: 'ok', text: `${paths.shims} first on PATH` }
}

const shimsPresent = (config: Config | null, pathEnv: string | undefined): DoctorCheck => {
  const names = [...new Set([...Object.keys(builtins), ...Object.keys(config?.harness ?? {})])]
  const bad = names.reduce((memo: string[], name: string) => {
    const h = find(name, config)
    if (!h) return memo
    if (!realBin(h.bin, { path: pathEnv })) return memo // not installed → no shim expected
    const file = path.join(paths.shims, h.bin)
    let why: string | null = null
    if (!fs.existsSync(file)) why = 'missing'
    else if (fs.lstatSync(file).isSymbolicLink()) why = 'not a symlink' // bins are files; only aliases link
    else if (!fs.readFileSync(file, 'utf8').includes(MARKER)) why = 'not barrito-generated'
    if (why) memo.push(`${h.bin} (${why})`)
    return memo
  }, [])
  if (bad.length) return { level: 'fail', text: `shim problems: ${bad.join(', ')} — run barrito shim` }
  const installed = names.filter((name) => { const h = find(name, config); return h && realBin(h.bin, { path: pathEnv }) })
  return { level: 'ok', text: `shims present (${installed.join(', ')})` }
}

const router = async (config: Config | null, { fetch: f, exec, pf }: { fetch?: FetchJson; exec: Exec; pf: 'darwin' | 'linux' }): Promise<DoctorCheck> => {
  const svc = service.status({ exec })
  const data = parseStatus(await fetchJson(`${base(config)}/status`, { fetch: f }))
  if (data) {
    const pid = data.pid ?? svc.pid ?? '?'
    const dur = data.uptime != null ? `, ${human(data.uptime * 1000)}` : ''
    return { level: 'ok', text: `router up 127.0.0.1:${port(config)} (pid ${pid}${dur})` }
  }
  const health = await fetchJson(`${base(config)}/health`, { fetch: f })
  if (health) return { level: 'ok', text: `router up 127.0.0.1:${port(config)}` }
  if (svc.running) {
    return pf === 'linux'
      ? { level: 'warn', text: `router service loaded but not answering on :${port(config)} — systemctl --user restart ${unit}` }
      : { level: 'warn', text: `router service loaded but not answering on :${port(config)} — launchctl kickstart -k gui/${launchd.uid()}/${service.label}` }
  }
  return { level: 'fail', text: `router not running — barrito serve, or barrito init to install the service` }
}

const legacy = (exec: Exec): DoctorCheck | null => {
  try {
    launchd.run(exec, ['print', `gui/${launchd.uid()}/${service.legacy}`])
  } catch {
    return null
  }
  return {
    level: 'fail',
    text: `legacy claude-router still loaded — launchctl bootout gui/${launchd.uid()}/${service.legacy}, then barrito init`,
  }
}

const loggedIn = (dir: string): boolean => account(dir).loggedIn

// keyring names read as "keychain item"; env:/file: refs print as themselves
const label = (ref: string): string => keychain.kind(ref) === 'keyring' ? `keychain item "${ref}"` : ref

// a get that throws (linux keyring unavailable) is not the same as a missing secret
const read = (kc: Keychain, ref: string): { ok: boolean; missing: boolean } => {
  try { return { ok: kc.get(ref) != null, missing: true } } catch { return { ok: false, missing: false } }
}

const identityBits = (kc: Keychain, id: string, identity: Identity): DoctorCheck => {
  const dirOk = Boolean(identity.claude_config_dir) && fs.existsSync(identity.claude_config_dir)
  const parts: Array<['ok' | 'warn' | 'fail', string]> = []
  parts.push(dirOk && loggedIn(identity.claude_config_dir)
    ? ['ok', 'claude login']
    : ['fail', dirOk ? 'claude not logged in (claude /login)' : 'claude config dir missing'])
  const gw = identity.keychain?.gateway
  if (gw) {
    const r = read(kc, gw)
    parts.push(r.ok
      ? ['ok', 'gateway key']
      : r.missing
        ? ['fail', `gateway ${label(gw)} missing`]
        : ['warn', `gateway ${label(gw)} unreadable — no keyring (env:/file: refs work without one)`])
  } else {
    parts.push(['fail', 'gateway keychain item not configured'])
  }
  const cur = identity.keychain?.cursor
  if (cur) {
    const r = read(kc, cur)
    parts.push(r.ok
      ? ['ok', 'cursor key']
      : ['warn', `cursor ${label(cur)} ${r.missing ? 'missing' : 'unreadable — no keyring'}`])
  }
  const level = parts.some((p) => p[0] === 'fail') ? 'fail' : parts.some((p) => p[0] === 'warn') ? 'warn' : 'ok'
  return { level, text: `${id}: ${parts.map((p) => p[1]).join(' · ')}` }
}

const baseUrl = (config: Config | null, read: Settings['read'], id: string, identity: Identity): DoctorCheck | null => {
  if (!identity.claude_config_dir || !fs.existsSync(identity.claude_config_dir)) return null
  const want = `http://127.0.0.1:${port(config)}`
  const url = read(identity.claude_config_dir)?.env?.ANTHROPIC_BASE_URL
  if (url === want) return { level: 'ok', text: `${id}: ANTHROPIC_BASE_URL → ${want}` }
  return { level: 'fail', text: `${id}: ANTHROPIC_BASE_URL is ${url ?? 'unset'} (want ${want}) — barrito init` }
}

const modelsBits = (config: Config | null, read: Settings['read']): DoctorCheck[] => {
  const models = catalog.cached({ statePath: paths.state })
  if (!models) return [{ level: 'warn', text: 'no gateway catalog cached — barrito models sync fetches it' }]
  const { missing, fresh } = nudges(config, models, { read })
  const out: DoctorCheck[] = [missing.length
    ? { level: 'fail', text: `models missing from gateway catalog: ${missing.join(', ')} — barrito models sync` }
    : { level: 'ok', text: 'picker + fallback models all in gateway catalog' }]
  if (fresh.length) out.push({ level: 'warn', text: `${fresh.length} new gateway models match your rules → barrito models sync` })
  return out
}

// a host (emdash/Conductor) that started before the shims were installed still has the old
// PATH — one line per host, not per process
const hosts = (exec: Exec | undefined): DoctorCheck[] => {
  if (!exec) return []
  let list: string
  try { list = exec('ps', ['-axo', 'pid=,comm=']) } catch { return [] }
  let shimsAt: number
  try { shimsAt = fs.statSync(paths.shims).mtimeMs } catch { return [] }
  const stale = list.split('\n').reduce<Record<string, true>>((memo, line: string) => {
    const hit = line.match(/^\s*(\d+)\s+(.+)$/)
    if (!hit) return memo
    const pid = hit[1] ?? ''
    const comm = hit[2] ?? ''
    const name = comm.toLowerCase().match(/emdash|conductor/)
    if (!name) return memo
    let start = NaN
    try { start = Date.parse(exec('ps', ['-o', 'lstart=', '-p', pid])) } catch {}
    if (!Number.isNaN(start) && start < shimsAt) memo[name[0]] = true
    return memo
  }, {})
  return Object.keys(stale).map((name) => ({ level: 'warn' as const, text: `${name} started before the shims install → restart ${name}` }))
}

// launchctl/ps chatter goes to stderr by default; doctor reports findings itself
const quiet = (bin: string, args: string[], o: ExecFileSyncOptions = {}): string =>
  execFileSync(bin, args, { ...o, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] })

const onPath = (pathEnv: string | undefined, bin: string): boolean =>
  (pathEnv ?? '').split(':').filter(Boolean).some((d) => xok(path.join(real(d) ?? d, bin)))

// rtk-enabled identities compress tool output through the rtk binary before it hits the model
const rtkEnabled = (config: Config | null): boolean => {
  const ids = Object.keys(config?.identities ?? {})
  if (!ids.length) return config?.transforms?.rtk ?? true
  return ids.some((id) => config?.identities?.[id]?.transforms?.rtk ?? config?.transforms?.rtk ?? true)
}

const rtkCheck = (config: Config | null, pathEnv: string | undefined): DoctorCheck | null => {
  if (!rtkEnabled(config) || onPath(pathEnv, 'rtk')) return null
  return { level: 'warn', text: 'rtk enabled but not on PATH — brew install rtk, then barrito doctor' }
}

// macOS: only terminal-notifier can put the burrito on a notice (osascript cannot show an image)
const notifierCheck = (pf: 'darwin' | 'linux', pathEnv: string | undefined): DoctorCheck | null => {
  if (pf !== 'darwin' || onPath(pathEnv, 'terminal-notifier')) return null
  return { level: 'warn', text: 'notifications use osascript (no burrito icon) — brew install terminal-notifier' }
}

const tilde = (p: string): string => p.startsWith(home()) ? `~${p.slice(home().length)}` : p

type Env = Record<string, string | undefined>
type KeyringCheck = (o: { exec?: Exec }) => boolean

// linux-only: linger, the rc PATH line, and keyring availability
const linuxBits = (config: Config | null, { exec, env, keyring }: { exec: Exec; env: Env; keyring: KeyringCheck }): DoctorCheck[] => {
  const out: DoctorCheck[] = []
  try {
    if (!/^Linger=yes\b/m.test(exec('loginctl', ['show-user', env.USER ?? '', '--property=Linger']))) {
      out.push({ level: 'warn', text: `linger not enabled — loginctl enable-linger${env.USER ? ` ${env.USER}` : ''} keeps the router alive after logout` })
    }
  } catch {} // no loginctl → no user session; `barrito serve --detach` territory, not a doctor complaint

  const rc = rcOf({ home: home(), shell: env.SHELL })
  out.push(rc.present
    ? { level: 'ok', text: `~/.local/shims prepended in ${tilde(rc.file)}` }
    : { level: 'fail', text: `~/.local/shims not in ${tilde(rc.file)} — add '${rc.lines[0]}' (barrito init)` })

  const refs = Object.values(config?.identities ?? {}).flatMap((i) => [i.keychain?.gateway, i.keychain?.cursor])
  if (refs.some((r) => r != null && keychain.kind(r) === 'keyring') && !keyring({ exec })) {
    out.push({ level: 'warn', text: 'secret-tool unavailable (no keyring) — keyring refs are unreadable; rerun barrito init for env:/file: refs, or install gnome-keyring + secret-tool' })
  }
  return out
}

// CI (GITHUB_ACTIONS): no service manager, no hosts, no rc — env vars, health, and env:/file: refs only
const ciChecks = (config: Config | null, { pathEnv, env }: { pathEnv: string | undefined; env: Env }): DoctorCheck[] => {
  const out = [shimsFirst(pathEnv), shimsPresent(config, pathEnv)]
  const bPort = env.BARRITO_PORT
  out.push(bPort
    ? { level: 'ok', text: `BARRITO_PORT=${bPort}` }
    : { level: 'warn', text: `BARRITO_PORT not set — the router falls back to config port ${config?.port ?? 4141}; barrito ci exports it` })
  const bId = env.BARRITO_IDENTITY
  out.push(bId
    ? { level: 'ok', text: `BARRITO_IDENTITY=${bId}` }
    : { level: 'warn', text: `BARRITO_IDENTITY not set — everything routes to "${config?.default ?? 'personal'}" (barrito ci --identity …)` })
  return out
}

const ciHealth = async (config: Config | null, { fetch: f }: { fetch?: FetchJson }): Promise<DoctorCheck> => {
  const up = await fetchJson(`${base(config)}/health`, { fetch: f })
  return up
    ? { level: 'ok', text: `router up 127.0.0.1:${port(config)}` }
    : { level: 'fail', text: `router not answering on :${port(config)} — barrito ci starts it detached and waits for /health` }
}

// a keyring name can't resolve in CI; env: must be set, file: must be readable
const readable = (file: string): boolean => {
  try { fs.accessSync(file, fs.constants.R_OK); return true } catch { return false }
}

const ciRef = (id: string, ref: string | undefined, env: Env): DoctorCheck => {
  if (!ref) return { level: 'fail', text: `${id}: gateway secret not configured` }
  const kind = keychain.kind(ref)
  if (kind === 'keyring') {
    return { level: 'fail', text: `${id}: gateway ref "${ref}" is a keyring name — CI has no keyring; use env:VAR or file:/path (barrito ci --gateway-key env:…)` }
  }
  if (kind === 'env') {
    return env[ref.slice(4)]
      ? { level: 'ok', text: `${id}: gateway ${ref}` }
      : { level: 'fail', text: `${id}: ${ref} not set — add it to the step env` }
  }
  const file = expand(ref.slice(5))
  return readable(file)
    ? { level: 'ok', text: `${id}: gateway ${ref}` }
    : { level: 'fail', text: `${id}: ${ref} not readable` }
}

export const diagnose = async (
  config: Config | null,
  {
    fetch: f,
    exec = quiet,
    pathEnv = process.env.PATH,
    keychain: kc = keychain,
    settings = { read: readSettings },
    env = process.env,
    keyring = ({ exec: e }) => platform() === 'linux' ? linuxKeyring({ exec: e }) : true,
  }: DiagnoseOpts = {},
): Promise<DoctorCheck[]> => {
  const pf = platform()
  if (env.GITHUB_ACTIONS === 'true') {
    const out = ciChecks(config, { pathEnv, env })
    out.push(await ciHealth(config, { fetch: f }))
    out.push(...Object.entries(config?.identities ?? {}).map(([id, identity]) => ciRef(id, identity.keychain?.gateway, env)))
    return out
  }

  const results = [shimsFirst(pathEnv), shimsPresent(config, pathEnv), await router(config, { fetch: f, exec, pf })]
  if (pf === 'darwin') {
    const legacyLine = legacy(exec)
    if (legacyLine) results.push(legacyLine)
  }
  if (pf === 'linux') results.push(...linuxBits(config, { exec, env, keyring }))

  for (const [id, identity] of Object.entries(config?.identities ?? {})) {
    results.push(identityBits(kc, id, identity))
    const url = baseUrl(config, settings.read, id, identity)
    if (url) results.push(url)
  }

  const rtk = rtkCheck(config, pathEnv)
  if (rtk) results.push(rtk)
  const notifier = notifierCheck(pf, pathEnv)
  if (notifier) results.push(notifier)
  results.push(...modelsBits(config, settings.read), ...hosts(exec))
  return results
}

export default async (argv: string[], ctx: CommandCtx, opts: DiagnoseOpts = {}): Promise<void> => {
  const { values } = parseArgs({ args: argv, options: { json: { type: 'boolean' } } })
  const results = await diagnose(ctx.config, opts)
  if (values.json) {
    ctx.print(JSON.stringify(results, null, 2))
    if (results.some((r) => r.level === 'fail')) return ctx.exit(1)
    return
  }
  const mark = { ok: pc.green('✓'), warn: pc.yellow('!'), fail: pc.red('✗') }
  results.forEach((r) => ctx.print(`${mark[r.level]} ${r.text}`))
  if (results.some((r) => r.level === 'fail')) return ctx.exit(1)
}
