import { parseArgs } from 'node:util'
import fs from 'node:fs'
import { join } from 'node:path'
import { paths, root } from '../paths.ts'
import { builtins, find, MARKER } from '../harnesses.ts'
import type { CommandCtx, CommandFn, Config, Harness, Print } from '../types.ts'

export type ShimCtx = CommandCtx & { bin?: string; node?: string }
type MigratedShimCtx = Omit<ShimCtx, 'config' | 'exit'> & {
  config: Config | { harness: {} }
  exit: () => void
}

// bake absolute node + barrito paths so shims work with a scrubbed PATH
const bake = (bin?: string, node?: string): string => {
  let js = bin ?? process.argv[1] ?? 'barrito'
  try { js = fs.realpathSync(js) } catch {}
  return `${JSON.stringify(node ?? process.execPath)} ${JSON.stringify(js)}`
}

const content = (f: string): string | null => {
  try { return fs.readFileSync(f, 'utf8') } catch { return null }
}

interface Target {
  file: string
  name: string
  link?: string
}

export const writeShims = ({
  config,
  harnesses,
  dir,
  force,
  bin,
  node,
  print,
}: {
  config: Pick<Config, 'harness'>
  harnesses: string[]
  dir: string
  force: boolean
  bin?: string
  node?: string
  print: Print
}): { written: string[]; refused: string[] } => {
  const resolved = harnesses.flatMap((name) => {
    const harness = find(name, config)
    return harness ? [{ name, harness }] : []
  })
  if (resolved.length !== harnesses.length) return { written: [], refused: [] }

  fs.mkdirSync(dir, { recursive: true })
  const targets = resolved.reduce<Target[]>((memo, { name, harness }) => {
    memo.push({ file: join(dir, harness.bin), name })
    for (const alias of harness.aliases ?? []) memo.push({ file: join(dir, alias), name, link: harness.bin })
    return memo
  }, [])

  const foreign = targets.filter((target) => {
    if (target.link) return fs.existsSync(target.file) && !fs.lstatSync(target.file).isSymbolicLink()
    const c = content(target.file)
    return c !== null && !c.includes(MARKER)
  })
  if (foreign.length && !force) return { written: [], refused: foreign.map(({ file }) => file) }

  const shimTemplate = fs.readFileSync(join(root(), 'templates', 'shim.sh'), 'utf8')
  const paths = resolved.reduce<string[]>((memo, { name, harness }) => {
    const file = join(dir, harness.bin)
    fs.writeFileSync(file, shimTemplate.replaceAll('__BARRITO__', bake(bin, node)).replaceAll('__HARNESS__', name))
    fs.chmodSync(file, 0o755)
    print(`wrote ${file}`)
    memo.push(file)
    for (const alias of harness.aliases ?? []) {
      const link = join(dir, alias)
      if (fs.existsSync(link)) fs.rmSync(link)
      fs.symlinkSync(harness.bin, link)
      print(`linked ${link} → ${harness.bin}`)
      memo.push(link)
    }
    return memo
  }, [])
  return { written: paths, refused: [] }
}

async function shim(argv: string[], ctx: ShimCtx): Promise<void>
async function shim(argv: string[], ctx: MigratedShimCtx): Promise<void>
async function shim(argv: string[], ctx: ShimCtx | MigratedShimCtx): Promise<void> {
  const { values, positionals } = parseArgs({
    args: argv,
    allowPositionals: true,
    options: { dir: { type: 'string' }, force: { type: 'boolean' } },
  })
  const dir = values.dir ?? paths.shims
  const config = ctx.config
  const names = positionals.length
    ? positionals
    : [...new Set([...Object.keys(builtins), ...Object.keys(config.harness ?? {})])]
  const harnesses = names.map((name) => ({ name, h: find(name, config) }))
  const unknown = harnesses.filter((x) => !x.h)
  if (unknown.length) {
    console.error(`barrito: unknown harness: ${unknown.map((x) => x.name).join(', ')}`)
    ctx.exit(2)
    return
  }

  const result = writeShims({
    config,
    harnesses: names,
    dir,
    force: values.force ?? false,
    bin: ctx.bin,
    node: ctx.node,
    print: ctx.print,
  })
  if (result.refused.length) {
    for (const file of result.refused) console.error(`barrito: refusing to overwrite ${file} (not generated by barrito); use --force`)
    ctx.exit(1)
    return
  }
}

export default shim satisfies CommandFn
