#!/usr/bin/env bash
# generated by barrito — do not edit; run `barrito shim` to regenerate
eval "$(__BARRITO__ env --shell --harness __HARNESS__ --self "$0")" || exit $?
[ -n "${BARRITO_REAL_BIN:-}" ] || exit 127
exec "$BARRITO_REAL_BIN" "$@"
