#!/usr/bin/env bash
# packed-tarball smoke: build, pack, install into a temp prefix, and prove the
# dist runs standalone — templates resolve via root(), no .ts files shipped.
# Never touches the real HOME, shims, Keychain or port 4141.
set -euo pipefail
cd "$(dirname "$0")/.."

yarn build

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# pack into the temp dir so the repo root keeps nothing
npm pack --pack-destination "$tmp"
npm install -g --prefix "$tmp" "$tmp"/barrito-*.tgz
B="$tmp/bin/barrito"
test -x "$B"

version=$(node -p "require('./package.json').version")
[ "$("$B" --version)" = "$version" ]
"$B" --help | grep -q '^usage: barrito <command>'

# the package must run without any .ts files of its own (deps' .d.ts don't count)
[ -z "$(find "$tmp/lib/node_modules/barrito/dist" -name '*.ts')" ]
[ ! -e "$tmp/lib/node_modules/barrito/src" ]

# temp HOME + config + git repo + a stub codex on PATH
mkdir -p "$tmp/home" "$tmp/state" "$tmp/shims" "$tmp/stubs" "$tmp/repo"
cat > "$tmp/config.toml" <<EOF
port = 4141
default = "ci"

[identities.ci]
claude_config_dir = "$tmp/home/.claude"
fallback = ["zai/glm-5.3"]
keychain.gateway = "env:AI_GATEWAY_API_KEY"
EOF
git init -q "$tmp/repo"
printf '#!/bin/sh\n' > "$tmp/stubs/codex"
chmod +x "$tmp/stubs/codex"

export BARRITO_HOME="$tmp/home" BARRITO_CONFIG="$tmp/config.toml" \
  BARRITO_STATE="$tmp/state" BARRITO_SHIMS="$tmp/shims" BARRITO_LOG="$tmp/barrito.log"
export PATH="$tmp/stubs:$PATH"

"$B" which "$tmp/repo" | grep -q '^ci  ← default$'
"$B" env --shell --harness codex "$tmp/repo" > "$tmp/env.sh"
grep -q "OPENAI_BASE_URL='http://127.0.0.1:4141/gateway/v1'" "$tmp/env.sh"
grep -q "OPENAI_API_KEY='barrito:ci'" "$tmp/env.sh"
grep -q "BARRITO_IDENTITY='ci'" "$tmp/env.sh"

# templates ship in the tarball and resolve from the installed dist via root()
"$B" shim --dir "$tmp/shims" claude
grep -q 'generated by barrito' "$tmp/shims/claude"

echo "smoke ok — packed tarball installs and runs from dist/"
