import fsx from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import { builtins, realBin } from './harnesses.ts'
import { get as keychainGet, has as keychainHas, kind as keychainKind } from './keychain/index.ts'
import * as service from './service/index.ts'
import { unit } from './service/systemd.ts'
import { platform } from './paths.ts'
import { load as loadConfig } from './config.ts'
import { account } from './claude.ts'
import type { Builtin, ClaudeSettings, Exec, Keychain, PickerRow } from './types.ts'

export const marker = 'generated by barrito'

// the marked PATH block init writes into the shell rc (and uninstall removes, whole)
export const rcOpen = '# >>> barrito >>>'
export const rcClose = '# <<< barrito <<<'

const byName: Record<string, Builtin> = builtins

const defaultExec: Exec = (bin, args) => execFileSync(bin, args, { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] })
const json = (fs: typeof fsx, file: string): unknown => {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')) } catch { return null }
}
const isObj = (v: unknown): v is Record<string, unknown> => v !== null && typeof v === 'object' && !Array.isArray(v)
const exists = (fs: typeof fsx, p: string): boolean => { try { return fs.existsSync(p) } catch { return false } }

const KEYCHAIN = ['Vercel AI Gateway', 'Vercel AI Gateway Work', 'Cursor', 'Cursor Work']
const ENVRC_VARS = ['CURSOR_API_KEY', 'AI_GATEWAY_API_KEY', 'ANTHROPIC_CUSTOM_HEADERS']
const desktop = (home: string, name: string): string => path.join(home, '.local', 'share', 'applications', `${name}.desktop`)
const HOSTS: [string, (home: string, pf: 'darwin' | 'linux') => string[]][] = [
  ['emdash', (home, pf) => pf === 'linux'
    ? [desktop(home, 'emdash'), path.join(home, 'emdash')]
    : [path.join(home, 'emdash')]],
  ['conductor', (home, pf) => pf === 'linux'
    ? [desktop(home, 'conductor'), path.join(home, 'conductor')]
    : ['/Applications/Conductor.app', path.join(home, 'conductor'), path.join(home, 'Library', 'Application Support', 'Conductor')]],
]

export type Shell = 'zsh' | 'bash' | 'fish'

export interface Rc {
  shell: Shell
  file: string
  present: boolean
  lines: string[]
}

export interface RcOpts {
  home: string
  shell?: string
  fs?: typeof fsx
  platform?: 'darwin' | 'linux'
}

const SHELLS: readonly string[] = ['zsh', 'bash', 'fish']

const shellOf = (shell: string | undefined, pf: 'darwin' | 'linux'): Shell => {
  const base = path.basename(shell ?? '').toLowerCase()
  return SHELLS.includes(base) ? base as Shell : pf === 'linux' ? 'bash' : 'zsh'
}

// the PATH line init adds, per shell — the same text used to recognize an existing equivalent
export const rcLines = (shell: Shell): string[] =>
  shell === 'fish' ? ['fish_add_path -p ~/.local/shims'] : ['export PATH="$HOME/.local/shims:$PATH"']

const esc = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

// "already there" = our marker, or a hand-written line that prepends the shims dir
// (first entry, so nothing shadows it) — e.g. the user's existing `export PATH="$HOME/.local/shims:$PATH"`
const rcPresent = (text: string, shell: Shell, home: string): boolean => {
  if (text.includes(rcOpen)) return true
  const shims = ['\\$HOME/\\.local/shims', '\\$\\{HOME\\}/\\.local/shims', esc(path.join(home, '.local', 'shims'))]
  if (shell === 'fish') return new RegExp('^\\s*fish_add_path\\b[^\\n]*\\.local/shims', 'm').test(text)
  return new RegExp(`^\\s*export\\s+PATH\\s*=\\s*["']?(?:${shims.join('|')}):`, 'm').test(text)
}

export const rcOf = ({ home, shell, fs = fsx, platform: pf = platform() }: RcOpts): Rc => {
  const sh = shellOf(shell, pf)
  const file = sh === 'zsh'
    ? path.join(home, '.zshrc')
    : sh === 'bash'
      ? path.join(home, pf === 'darwin' ? '.bash_profile' : '.bashrc')
      : path.join(home, '.config', 'fish', 'conf.d', 'barrito.fish')
  let text = ''
  try { text = fs.readFileSync(file, 'utf8') } catch {}
  return { shell: sh, file, present: rcPresent(text, sh, home), lines: rcLines(sh) }
}

export interface ClaudeAccount {
  loggedIn: boolean
  email: string | null
}

export type Creds = (fs: typeof fsx, dir: string, home: string) => ClaudeAccount

export interface Agent {
  name: string
  version: string
  path: string
}

export interface EnvrcLink {
  path: string
  target: string
}

export interface EnvrcKey {
  file: string
  var: string
}

export interface Legacy {
  launchd: boolean
  shims: string[]
  envrcLinks: EnvrcLink[]
  envrcKeys: EnvrcKey[]
  settingsBaseUrl: string | null
  modelPicker: PickerRow[]
  statusLine: string | null
}

export interface ClaudeDir extends ClaudeAccount {
  dir: string
}

export interface Detected {
  agents: Agent[]
  hosts: string[]
  legacy: Legacy
  claudeDirs: ClaudeDir[]
  keychain: Record<string, boolean>
  rc: Rc
  router: { installed: boolean; running: boolean }
}

export interface DetectOpts {
  home: string
  exec?: Exec
  fs?: typeof fsx
  path?: string
  keychain?: Keychain | ((service: string) => string | null)
  creds?: Creds
  shell?: string
}

const agents = ({ home, exec, fs, path: pathEnv }: { home: string; exec: Exec; fs: typeof fsx; path: string | undefined }) =>
  Object.keys(builtins).reduce<Agent[]>((memo, name) => {
    const real = realBin(byName[name]!.bin, { path: pathEnv, shims: path.join(home, '.local', 'shims') })
    if (!real) return memo
    let version = ''
    try { version = exec(real, ['--version']).trim().split('\n')[0] ?? '' } catch {}
    memo.push({ name, version, path: real })
    return memo
  }, [])

const hosts = ({ home, fs }: { home: string; fs: typeof fsx }) => {
  const pf = platform()
  return HOSTS.reduce<string[]>((memo, [name, candidates]) => {
    if (candidates(home, pf).some((p) => exists(fs, p))) memo.push(name)
    return memo
  }, [])
}

// legacy = anything in the shim dir we didn't generate (hand shims, helper scripts,
// symlinks to hand shims). Generated shims carry the marker; their `agent` alias resolves to one.
const legacyShims = ({ home, fs }: { home: string; fs: typeof fsx }): string[] => {
  const dir = path.join(home, '.local', 'shims')
  if (!exists(fs, dir)) return []
  return fs.readdirSync(dir).reduce<string[]>((memo, name) => {
    const file = path.join(dir, name)
    const stat = fs.lstatSync(file)
    const content = (): string | null => {
      try {
        return fs.readFileSync(stat.isSymbolicLink() ? path.resolve(dir, fs.readlinkSync(file)) : file, 'utf8')
      } catch { return null }
    }
    if ((content() ?? '').includes(marker)) return memo
    memo.push(file)
    return memo
  }, [])
}

const envrcLinks = ({ home, fs }: { home: string; fs: typeof fsx }): EnvrcLink[] => {
  const dir = path.join(home, 'emdash', 'worktrees')
  if (!exists(fs, dir)) return []
  return fs.readdirSync(dir).reduce<EnvrcLink[]>((memo, name) => {
    const file = path.join(dir, name, '.envrc')
    try {
      if (fs.lstatSync(file).isSymbolicLink()) memo.push({ path: file, target: fs.readlinkSync(file) })
    } catch {}
    return memo
  }, [])
}

const envrcKeys = ({ home, fs }: { home: string; fs: typeof fsx }): EnvrcKey[] => {
  const code = path.join(home, 'Code')
  if (!exists(fs, code)) return []
  return fs.readdirSync(code).reduce<EnvrcKey[]>((memo, owner) => {
    const file = path.join(code, owner, '.envrc')
    let text = ''
    try { text = fs.readFileSync(file, 'utf8') } catch { return memo }
    text.split('\n').forEach((line) => {
      const hit = /^export\s+([A-Z0-9_]+)=/.exec(line.trim())
      if (!hit) return
      const name = hit[1] ?? ''
      if (!ENVRC_VARS.includes(name)) return
      memo.push({ file, var: name })
    })
    return memo
  }, [])
}

const creds: Creds = (fs, dir, home) => account(dir, { fs, home })

// login state for every configured claude dir — the config's identities when it has
// any, the two built-in defaults on a fresh machine
const dirsOf = (home: string, fs: typeof fsx): string[] => {
  let configured: string[] = []
  try {
    configured = Object.values(loadConfig().identities)
      .map((identity) => identity.claude_config_dir)
      .filter((dir): dir is string => typeof dir === 'string' && dir.length > 0)
  } catch {}
  const dirs = configured.length ? configured : ['.claude', '.claude-personal'].map((name) => path.join(home, name))
  return [...new Set(dirs)]
}

// the keyring-kind keychain names an identity set uses — env:/file: refs are never probed
export const keyringRefs = (identities: Record<string, { keychain?: Record<string, string | undefined> }>): string[] =>
  Object.values(identities).flatMap((identity) => Object.values(identity.keychain ?? {}))
    .filter((ref): ref is string => typeof ref === 'string' && ref.length > 0 && keychainKind(ref) === 'keyring')

// probe with has() where the adapter offers it (macOS: attributes only, no -w — probing
// an item another tool made never prompts); a get that throws reads as "no key", never a crash
export const probe = (refs: string[], keychain: Keychain | ((service: string) => string | null)): Record<string, boolean> => {
  const kc = typeof keychain === 'function' ? { get: keychain } : keychain
  return [...new Set(refs)].reduce<Record<string, boolean>>((memo, name) => {
    try { memo[name] = kc.has ? kc.has(name) : kc.get(name) != null } catch { memo[name] = false }
    return memo
  }, {})
}

// the built-in defaults plus every configured identity's keyring names — a custom
// identity must be probed too, or the cursor-keys migrate action re-plans forever
const refsOf = (): string[] => {
  let configured: string[] = []
  try { configured = keyringRefs(loadConfig().identities) } catch {}
  return [...new Set([...KEYCHAIN, ...configured])]
}

export const detect = ({
  home,
  exec = defaultExec,
  fs = fsx,
  path: pathEnv = process.env.PATH,
  keychain = { get: keychainGet, has: keychainHas },
  creds: readCreds = creds,
  shell = process.env.SHELL,
}: DetectOpts = {} as DetectOpts): Detected => {
  const pf = platform()
  const claude = path.join(home, '.claude')
  const parsed = json(fs, path.join(claude, 'settings.json'))
  const settingsJson: ClaudeSettings = isObj(parsed) ? (parsed as ClaudeSettings) : {}

  return {
    agents: agents({ home, exec, fs, path: pathEnv }),
    hosts: hosts({ home, fs }),
    legacy: {
      // launchd is macOS-only; a stray plist on a linux box is not a live legacy service
      launchd: pf === 'darwin' && exists(fs, path.join(home, 'Library', 'LaunchAgents', `${service.legacy}.plist`)),
      shims: legacyShims({ home, fs }),
      envrcLinks: envrcLinks({ home, fs }),
      envrcKeys: envrcKeys({ home, fs }),
      settingsBaseUrl: settingsJson.env?.ANTHROPIC_BASE_URL ?? null,
      modelPicker: settingsJson.modelPicker?.options ?? [],
      statusLine: settingsJson.statusLine?.command ?? null,
    },
    claudeDirs: dirsOf(home, fs).map((dir) => ({ dir, ...readCreds(fs, dir, home) })),
    keychain: probe(refsOf(), keychain),
    rc: rcOf({ home, shell, fs, platform: pf }),
    router: {
      installed: pf === 'linux'
        ? exists(fs, path.join(home, '.config', 'systemd', 'user', `${unit}.service`))
        : exists(fs, path.join(home, 'Library', 'LaunchAgents', `${service.label}.plist`)),
      running: service.status({ exec }).running,
    },
  }
}
