import fs from 'node:fs'
import { dirname } from 'node:path'
import { paths } from './paths.ts'
import { get as keychainGet } from './keychain/index.ts'
import { configDirEnv } from './claude.ts'
import type { Builtin, Config, Harness, Identity, Keychain } from './types.ts'

export const MARKER = 'generated by barrito'

export const builtins: {
  claude: Builtin
  codex: Builtin
  opencode: Builtin
  'cursor-agent': Builtin
} & Record<string, Builtin> = {
  claude: { bin: 'claude', level: 'full' },
  codex: {
    bin: 'codex', level: 'gateway',
    env: { OPENAI_BASE_URL: '{gateway}/v1', OPENAI_API_KEY: '{handle}' },
  },
  opencode: {
    bin: 'opencode', level: 'gateway',
    env: {
      AI_GATEWAY_API_KEY: '{handle}',
      VERCEL_AI_GATEWAY_BASE_URL: '{gateway}/v1/ai',
      BARRITO_HANDLE: '{handle}',
    },
  },
  'cursor-agent': {
    bin: 'cursor-agent', level: 'env', aliases: ['agent'],
    env: { CURSOR_API_KEY: '{keychain:cursor}', AGENT_CLI_CREDENTIAL_STORE: 'file' },
  },
}

// opencode's "vercel" provider only takes a base URL/key from opencode.json (values
// support `{env:VAR}`), so the init worker merges this fragment; BARRITO_HANDLE carries
// the router handle in env. Codex is assumed to honor OPENAI_BASE_URL/OPENAI_API_KEY.
export const configFragments: {
  opencode: (opts?: { port?: number }) => {
    provider: { vercel: { npm: string; options: { baseURL: string; apiKey: string } } }
  }
} = {
  opencode: ({ port = 4141 }: { port?: number } = {}) => ({
    provider: {
      vercel: {
        npm: '@ai-sdk/vercel',
        options: { baseURL: `http://127.0.0.1:${port}/gateway/v1/ai`, apiKey: '{env:BARRITO_HANDLE}' },
      },
    },
  }),
}

export const find = (name: string, config: { harness?: Config['harness'] } | null | undefined): Harness | null => {
  const byName = (n: string): Harness | null => {
    const custom = config?.harness?.[n]
    const builtin = builtins[n]
    if (!builtin && !custom) return null
    return {
      name: n,
      bin: custom?.bin ?? builtin?.bin ?? n,
      level: custom?.level ?? builtin?.level ?? 'gateway',
      env: custom?.env ?? builtin?.env,
      aliases: custom?.aliases ?? builtin?.aliases,
    }
  }
  const direct = byName(name)
  if (direct) return direct
  const names = [...Object.keys(builtins), ...Object.keys(config?.harness ?? {})]
  const hit = names.find((n) => byName(n)?.aliases?.includes(name))
  return hit ? byName(hit) : null
}

type ExpandContext = {
  gateway: string
  handle: string
  identity: string
  keychainFor: (slot: string) => string | null
}

const expand = (value: string, ctx: ExpandContext): string | null => {
  let missing = false
  const out = String(value)
    .replaceAll('{gateway}', ctx.gateway)
    .replaceAll('{handle}', ctx.handle)
    .replaceAll('{identity}', ctx.identity)
    .replace(/\{keychain:([^}]+)\}/g, (_, slot) => {
      const key = ctx.keychainFor(slot)
      if (!key) {
        missing = true
        return ''
      }
      return key
    })
  return missing ? null : out
}

export const envFor = (
  harness: Partial<Harness> & Pick<Harness, 'bin'>,
  identity: Identity,
  {
    config,
    keychain,
    env = process.env,
  }: {
    config?: { port?: number } | null
    keychain?: Keychain | ((service: string) => string | null)
    env?: NodeJS.ProcessEnv
  } = {},
): Record<string, string> => {
  const templates = harness.env ?? {}
  const secret = Object.values(templates).some((v) => /\{keychain:/.test(String(v)))
  if (secret && harness.level !== 'env') {
    throw new Error(`barrito: harness "${harness.name ?? harness.bin}" is level "${harness.level ?? 'gateway'}" — {keychain:…} is only allowed at level "env"`)
  }

  const kc: Keychain = typeof keychain === 'function' ? { get: keychain } : (keychain ?? { get: keychainGet })
  const port = config?.port ?? 4141
  const ctx = {
    gateway: `http://127.0.0.1:${port}/gateway`,
    handle: `barrito:${identity.id}`,
    identity: identity.id,
    keychainFor: (slot: string): string | null => {
      const service = identity?.keychain?.[slot]
      if (!service) return null
      const key = kc.get(service)
      if (!key) console.error(`barrito: keychain "${service}" empty for ${identity.id} — ${harness.name ?? harness.bin} will fall back to its own login`)
      return key
    },
  }

  // old shim parity: env-level vars already set in the environment are never stomped
  const vars = Object.entries(templates).reduce<Record<string, string>>((out, [k, v]) => {
    if (harness.level === 'env' && (env[k] ?? '') !== '') return out
    const value = expand(v, ctx)
    if (value !== null) out[k] = value
    return out
  }, {})

  const full = harness.level === 'full'
    ? {
        ANTHROPIC_BASE_URL: `http://127.0.0.1:${port}`,
        CLAUDE_CONFIG_DIR: configDirEnv(identity.claude_config_dir),
        ANTHROPIC_CUSTOM_HEADERS: `x-barrito-identity: ${identity.id}`,
        BARRITO_IDENTITY: identity.id,
      }
    : { BARRITO_IDENTITY: identity.id }

  return Object.entries({ ...full, ...vars }).reduce<Record<string, string>>((out, [k, v]) => {
    if (v !== undefined && v !== null) out[k] = v
    return out
  }, {})
}

const xok = (f: string): boolean => {
  try { fs.accessSync(f, fs.constants.X_OK); return true } catch { return false }
}

const realpath = (f: string | undefined): string | null => {
  if (!f) return null
  try { return fs.realpathSync(f) } catch { return null }
}

const isShim = (f: string): boolean => {
  try {
    const fh = fs.openSync(f, 'r')
    const buf = Buffer.alloc(512)
    const n = fs.readSync(fh, buf, 0, 512, 0)
    fs.closeSync(fh)
    return buf.subarray(0, n).toString('utf8').split('\n').slice(0, 3).join('\n').includes(MARKER)
  } catch { return false }
}

// first executable on PATH outside the shims dir; never a barrito shim (--self / marker)
export const realBin = (
  bin: string,
  { path: pathEnv = process.env.PATH, shims = paths.shims, self }: { path?: string; shims?: string; self?: string } = {},
): string | null => {
  const skip = realpath(shims) ?? shims
  const selfReal = realpath(self)
  return (pathEnv ?? '').split(':').filter(Boolean).reduce<string | null>((found, dir) => {
    if (found) return found
    const d = realpath(dir) ?? dir
    if (d === skip) return found
    const candidate = `${d}/${bin}`
    if (!xok(candidate)) return found
    const resolved = fs.realpathSync(candidate)
    if ((selfReal && resolved === selfReal) || isShim(candidate) || dirname(resolved) === skip) return found
    return resolved
  }, null)
}
