import * as fsSync from 'node:fs'
import { join } from 'node:path'
import { bare, price } from './catalog.ts'
import { root } from './paths.ts'
import type {
  CatalogModel, Fs, ModelsConfig, PickerRow, SelectRules, Selected, Settings, Skipped, SyncDir, SyncResult, TierNote,
} from './types.ts'

const templates = (): string => join(root(), 'templates', 'agents')
const marker = /^\s*(?:#|<!--)\s*generated by barrito/m

const glob = (pattern: string) => {
  const re = new RegExp(`^${pattern.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*')}$`)
  return (id: string): boolean => re.test(id)
}

export const per1m = (n: number): string => `$${(n * 1e6).toFixed(2).replace(/\.00$/, '')}`

// long-context surcharge: { threshold, factor } from the pricing tiers, else null
const tiered = (pricing: CatalogModel['pricing']): TierNote | null => {
  const t = pricing?.input_tiers
  if (!t || t.length < 2) return null
  const [first, second] = t
  if (!first || !second) return null
  const factor = Number(second.cost) / Number(first.cost)
  if (!Number.isFinite(factor) || factor <= 1) return null
  return { threshold: first.max, factor }
}

const fmtTiers = ({ threshold, factor }: TierNote): string =>
  `${Number.isInteger(factor) ? factor : factor.toFixed(1)}× >${Math.round((threshold ?? Number.NaN) / 1000)}k`

const suffix = (m: CatalogModel, rules: SelectRules): '[1m]' | '' => {
  if (rules.suffix && Object.hasOwn(rules.suffix, m.id)) return rules.suffix[m.id] ?? ''
  return (m.context_window ?? 0) >= 1000000 && !m.pricing?.input_tiers ? '[1m]' : ''
}

const usable = (m: CatalogModel, need: string[]): boolean =>
  m.type === 'language' && need.every((tag) => (m.tags ?? []).includes(tag))

export const select = (catalog: CatalogModel[], rules: SelectRules = {}): Selected[] => {
  const need = rules.require ?? []
  const include = rules.include ?? []
  const exclude = rules.exclude ?? []
  const pins = new Set((rules.pin ?? []).map(bare))
  const passes = (m: CatalogModel): boolean => usable(m, need) && (rules.all || (
    !exclude.some((p) => glob(p)(m.id)) &&
    (!include.length || include.some((p) => glob(p)(m.id))) &&
    (rules.max_input_price == null || Number(m.pricing?.input) * 1e6 <= rules.max_input_price)
  ))
  return catalog
    .filter((m) => (pins.has(bare(m.id)) ? usable(m, need) : passes(m)))
    .map((m): Selected => ({
      id: `${m.id}${suffix(m, rules)}`,
      name: m.name,
      price: price(catalog, m.id),
      tiers: tiered(m.pricing),
    }))
}

// pins that exist in the catalog but fail the language/require checks
export const skipped = (catalog: CatalogModel[], rules: SelectRules = {}): Skipped[] => {
  const need = rules.require ?? []
  return (rules.pin ?? []).reduce<Skipped[]>((memo, id) => {
    const m = catalog.find((e) => e.id === bare(id))
    if (!m || usable(m, need)) return memo
    if (m.type !== 'language') return [...memo, { id, why: 'not a language model' }]
    return [...memo, { id, why: `missing ${need.filter((tag) => !(m.tags ?? []).includes(tag)).join(', ')}` }]
  }, [])
}

export const render = (selected: Selected[], config: ModelsConfig, { catalog = null, fs = fsSync, dir = templates() }: {
  catalog?: CatalogModel[] | null
  fs?: Fs
  dir?: string
} = {}): { modelPicker: { options: PickerRow[] }; agents: Record<string, string> } => {
  const labels = config.models?.labels ?? {}
  const byGroup = (a: Selected, b: Selected): number =>
    (a.id.split('/')[0] ?? '').localeCompare(b.id.split('/')[0] ?? '') || a.name.localeCompare(b.name)
  const options: PickerRow[] = [...selected].sort(byGroup).map((m) => ({
    model: `claude-code/${m.id}`,
    label: labels[m.id] ?? labels[bare(m.id)] ?? m.name,
    description: m.price
      ? `${m.name} · ${per1m(m.price.input)}/${per1m(m.price.output)} per 1M${m.tiers ? ` · ${fmtTiers(m.tiers)}` : ''}`
      : m.name,
  }))
  const agents = Object.entries(config.models?.agents ?? {}).reduce<Record<string, string>>((memo, [name, model]) => {
    if (catalog && !catalog.some((m) => m.id === bare(model))) return memo
    let template: string
    try {
      template = fs.readFileSync(join(dir, `${name}.md`), 'utf8')
    } catch {
      return memo
    }
    memo[`${name}.md`] = template.replace(/^model:.*$/m, `model: claude-code/${model.replace(/^claude-code\//, '')}`)
    return memo
  }, {})
  return { modelPicker: { options }, agents }
}

export const check = (config: ModelsConfig, catalog: CatalogModel[]): string[] => {
  const ids = new Set(catalog.map((m) => m.id))
  const wanted = [
    ...Object.values(config.identities ?? {}).flatMap((identity) => identity.fallback ?? []),
    ...Object.values(config.models?.agents ?? {}),
    ...(config.models?.pin ?? []),
  ]
  return [...new Set(wanted)].filter((id) => !ids.has(bare(id)))
}

const same = (a: PickerRow, b: PickerRow): boolean => JSON.stringify({ model: a.model, label: a.label, description: a.description })
  === JSON.stringify({ model: b.model, label: b.label, description: b.description })

export const sync = async ({ config, catalog, dryRun, all, settings, fs = fsSync }: {
  config: ModelsConfig
  catalog: CatalogModel[]
  dryRun?: boolean
  all?: boolean
  settings?: Settings
  fs?: Fs
}): Promise<SyncResult> => {
  const dirs = [...new Set(Object.values(config.identities ?? {})
    .map((identity) => identity.claude_config_dir).filter((d): d is string => !!d))]
  if (!dirs.length) throw new Error('no identities in config — run barrito init')

  const s: Settings = settings ?? await import('./settings.ts')
  const rules: SelectRules = { ...config.models, all }
  const selected = select(catalog, rules)
  const { modelPicker, agents } = render(selected, config, { catalog, fs })
  const wanted = modelPicker.options
  const known = new Set(catalog.map((m) => m.id))
  const out: SyncResult = {
    added: [], removed: [], unchanged: [], updated: [],
    dirs: [], missing: check(config, catalog), protected: [], skipped: skipped(catalog, rules),
  }

  const apply = (dir: string, current: { options: PickerRow[] } | undefined): void => {
    if (dryRun) return
    if (JSON.stringify(current) !== JSON.stringify(modelPicker)) s.merge(dir, { modelPicker })
    Object.entries(agents).forEach(([file, content]) => {
      const path = join(dir, 'agents', file)
      let prev: string | null = null
      try {
        prev = fs.readFileSync(path, 'utf8')
      } catch {
        prev = null
      }
      if (prev === content) return
      if (prev !== null && !marker.test(prev)) return out.protected.push(path)
      fs.mkdirSync(join(dir, 'agents'), { recursive: true })
      fs.writeFileSync(path, content)
    })
  }

  dirs.forEach((dir) => {
    const bucket: SyncDir = { dir, ok: true, added: [], removed: [], unchanged: [], updated: [] }
    try {
      const current = s.read(dir)?.modelPicker
      const have = current?.options ?? []
      const byModel = new Map(have.map((o): [string, PickerRow] => [o.model, o]))
      wanted.forEach((o) => {
        const prev = byModel.get(o.model)
        if (!prev) return bucket.added.push(bare(o.model))
        if (same(prev, o)) return bucket.unchanged.push(bare(o.model))
        bucket.updated.push(bare(o.model))
      })
      const keep = new Set(wanted.map((o) => o.model))
      have.forEach((o) => {
        if (keep.has(o.model)) return
        bucket.removed.push({ id: bare(o.model), reason: known.has(bare(o.model)) ? 'rules' : 'retired' })
      })
      apply(dir, current)
    } catch (err) {
      bucket.ok = false
      bucket.error = err instanceof Error ? err.message : String(err)
    }
    out.dirs.push(bucket)
  })

  const healthy = out.dirs.filter((d) => d.ok)
  out.added = [...new Set(healthy.flatMap((d) => d.added))]
  out.removed = [...new Map(healthy.flatMap((d) => d.removed).map((r) => [r.id, r])).values()]
  out.updated = [...new Set(healthy.flatMap((d) => d.updated))]
  out.unchanged = healthy.reduce<string[] | null>((memo, d) => (memo === null ? d.unchanged : memo.filter((id) => d.unchanged.includes(id))), null) ?? []
  return out
}
